<?php
/**
 * Foundation Framework
 *
 * @package   Weather
 * @copyright (©) 2010-2013, Olivier Jullien <https://github.com/ojullien>
 * @license   MIT <https://github.com/ojullien/Foundation/blob/master/LICENSE>
 *
 * PBRaider weather array structure definition.
 * The dtd is a list of WU keys to keep and the default values.
 *
 */
return array(
    'response'            => array(
        'dtd'      => '',
        'credit'   => '',
        'url'      => '',
        'expected' => '',
        'version'  => '' ),
    'current_observation' => array(
        'display_location'        => '',
        'observation_location'    => '',
        'observation_time_rfc822' => '',
        'weather'                 => '',
        'temp_c'                  => 0,
        'relative_humidity'       => '',
        'wind_dir'                => '',
        'wind_degrees'            => 0,
        'wind_kph'                => 0,
        'wind_gust_kph'           => '',
        'feelslike_c'             => '',
        'visibility_km'           => '',
        'icon'                    => '' ),
    'moon_phase'          => array(
        'sunrise' => array(
            'hour'   => '',
            'minute' => '' ),
        'sunset'  => array(
            'hour'   => '',
            'minute' => '' ) ),
    'forecast_date'       => '',
    'forecastday_short'   => array(
        0  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        1  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        2  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        3  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        4  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        5  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        6  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        7  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        8  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        9  => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        10 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        11 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        12 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        13 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        14 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        15 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        16 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        17 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        18 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ),
        19 => array(
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ) ),
    'forecastday'         => array(
        0 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ),
        1 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ),
        2 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ),
        3 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ),
        4 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ),
        5 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ),
        6 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ),
        7 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ),
        8 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ),
        9 => array(
            'date'        => array(
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ),
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => array(
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ),
            'avewind'     => array(
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ),
            'avehumidity' => 76 ) ),
);