<?php
/**
 * Foundation Framework
 *
 * @package   Weather
 * @copyright (©) 2010-2013, Olivier Jullien <https://github.com/ojullien>
 * @license   MIT <https://github.com/ojullien/Foundation/blob/master/LICENSE>
 *
 * PBRaider weather array structure definition.
 * The dtd is a list of WU keys to keep and the default values.
 *
 */
return [
    'response'            => [
        'dtd'      => '',
        'credit'   => '',
        'url'      => '',
        'expected' => '',
        'version'  => '' ],
    'current_observation' => [
        'display_location'        => '',
        'observation_location'    => '',
        'observation_time_rfc822' => '',
        'weather'                 => '',
        'temp_c'                  => 0,
        'relative_humidity'       => '',
        'wind_dir'                => '',
        'wind_degrees'            => 0,
        'wind_kph'                => 0,
        'wind_gust_kph'           => '',
        'feelslike_c'             => '',
        'visibility_km'           => '',
        'icon'                    => '' ],
    'moon_phase'          => [
        'sunrise' => [
            'hour'   => '',
            'minute' => '' ],
        'sunset'  => [
            'hour'   => '',
            'minute' => '' ] ],
    'forecast_date'       => '',
    'forecastday_short'   => [
        0  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        1  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        2  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        3  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        4  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        5  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        6  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        7  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        8  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        9  => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        10 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        11 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        12 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        13 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        14 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        15 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        16 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        17 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        18 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ],
        19 => [
            'icon'           => '',
            'title'          => '',
            'fcttext_metric' => '',
            'pop'            => '' ] ],
    'forecastday'         => [
        0 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ],
        1 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ],
        2 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ],
        3 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ],
        4 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ],
        5 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ],
        6 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ],
        7 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ],
        8 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ],
        9 => [
            'date'        => [
                'day'           => 7,
                'month'         => 2,
                'year'          => 2013,
                'monthname'     => 'février',
                'weekday_short' => 'jeu',
                'weekday'       => 'jeudi' ],
            'high'        => '5',
            'low'         => '-1',
            'conditions'  => 'Risque de pluie',
            'icon'        => 'chancerain',
            'pop'         => 40,
            'qpf_allday'  => 0.3,
            'snow_allday' => 0,
            'maxwind'     => [
                'kph'     => 26,
                'dir'     => 'NO',
                'degrees' => 323 ],
            'avewind'     => [
                'kph'     => 18,
                'dir'     => 'NO',
                'degrees' => 304 ],
            'avehumidity' => 76 ] ],
];
