<?php
/**
 * Foundation Framework
 *
 * @package   Weather
 * @copyright (©) 2010-2013, Olivier Jullien <https://github.com/ojullien>
 * @license   MIT <https://github.com/ojullien/Foundation/blob/master/LICENSE>
 *
 * Weather Underground array structure definition.
 * The dtd is used to decode the data from Weather Underground into an associative array used for PBR.
 * The dtd is a list of WU keys to keep and the default values.
 *
 * Rules:
 *
 * + DTD[key] => array( '__DEFAULT' => X )
 * This means that the PBR key does not exist in the WU data but has to be created into the PBR array, with the value X.
 *
 * Example:
 *
 * $DTD = array( 'the_key' => array( '__DEFAULT' => 'X' ) );
 * $WU = array( ... does not contain 'the_key' );
 * $Result = array( 'the_key' => 'X' );
 *
 * + DTD[key] => array( '__MOVE' => Y, '__DEFAULT' => X )
 * This means that the PBR key should receive the value of the WU key Y. The key exists in the WU data and it's an array
 * that contains the key Y. If the key Y does not exist in the WU data, the DTD key received the X default value.
 *
 * Examples:
 *
 * $DTD = array( 'the_key' => array( '__MOVE' => 'another_key', '__DEFAULT' => 'default_value' ) );
 * $WU = array( 'the_key' => array( 'another_key' => 'the_value' ) );
 * $Result = array( 'the_key' => 'the_value' );
 *
 * $DTD = array( 'the_key' => array( '__MOVE' => 'another_key', '__DEFAULT' => 'default_value' ) );
 * $WU = array( 'the_key' => array( 'not_the_key' => 'the_value' ) );
 * $Result = array( 'the_key' => 'default_value' );
 *
 */
return array(
    'response'            => array(
        'dtd'      => array( '__DEFAULT' => 'wu' ),
        'credit'   => array( '__DEFAULT' => 'Weather forecast from wunderground.com, delivered by Weather Underground®' ),
        'url'      => array( '__DEFAULT' => '' ),
        'expected' => array( '__DEFAULT' => '0.1' ),
        'version'  => '0.0' ),
    'current_observation' => array(
        'display_location'        => array(
            '__MOVE'    => 'full',
            '__DEFAULT' => '' ),
        'observation_location'    => array(
            '__MOVE'    => 'full',
            '__DEFAULT' => '' ),
        'observation_time_rfc822' => '',
        'weather'                 => '',
        'temp_c'                  => 0,
        'relative_humidity'       => '',
        'wind_dir'                => '',
        'wind_degrees'            => 0,
        'wind_kph'                => 0,
        'wind_gust_kph'           => 0,
        'feelslike_c'             => '',
        'visibility_km'           => '',
        'icon'                    => '',
        'ob_url'                  => '' ),
    'forecast'            => array(
        'txt_forecast'   => array(
            'date'        => '',
            'forecastday' => array(
                0  => array(
                    'period'         => 0,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                1  => array(
                    'period'         => 1,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                2  => array(
                    'period'         => 2,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                3  => array(
                    'period'         => 3,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                4  => array(
                    'period'         => 4,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                5  => array(
                    'period'         => 5,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                6  => array(
                    'period'         => 6,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                7  => array(
                    'period'         => 7,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                8  => array(
                    'period'         => 8,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                9  => array(
                    'period'         => 9,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                10 => array(
                    'period'         => 10,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                11 => array(
                    'period'         => 11,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                12 => array(
                    'period'         => 12,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                13 => array(
                    'period'         => 13,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                14 => array(
                    'period'         => 14,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                15 => array(
                    'period'         => 15,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                16 => array(
                    'period'         => 16,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                17 => array(
                    'period'         => 17,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                18 => array(
                    'period'         => 18,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ),
                19 => array(
                    'period'         => 19,
                    'icon'           => '',
                    'title'          => '',
                    'fcttext_metric' => '',
                    'pop'            => '' ) ) ),
        'simpleforecast' => array(
            'forecastday' => array(
                0 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ),
                1 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ),
                2 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ),
                3 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ),
                4 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ),
                5 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ),
                6 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ),
                7 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ),
                8 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ),
                9 => array(
                    'date'        => array(
                        'day'           => 0,
                        'month'         => 0,
                        'year'          => 0,
                        'monthname'     => '',
                        'weekday_short' => '',
                        'weekday'       => '' ),
                    'period'      => 1,
                    'high'        => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'low'         => array(
                        '__MOVE'    => 'celsius',
                        '__DEFAULT' => '' ),
                    'conditions'  => '',
                    'icon'        => '',
                    'pop'         => 0,
                    'qpf_allday'  => array(
                        '__MOVE'    => 'mm',
                        '__DEFAULT' => 0 ),
                    'snow_allday' => array(
                        '__MOVE'    => 'cm',
                        '__DEFAULT' => 0 ),
                    'maxwind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avewind'     => array(
                        'kph'     => 0,
                        'dir'     => '',
                        'degrees' => 0 ),
                    'avehumidity' => 0 ) ) ) ),
    'moon_phase'          => array(
        'sunrise' => array(
            'hour'   => '',
            'minute' => '' ),
        'sunset'  => array(
            'hour'   => '',
            'minute' => '' ) )
);