<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = [
//array( 'label'=>'TEST: /'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '/' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => $sBuffer10031 ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: \\'                       , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '\\' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => $sBuffer10031 ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: :'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . ':' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: *'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '*' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: ?'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '?' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: "'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '"' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: <'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '<' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: >'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '>' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: |'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '|' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: ""'                       , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '' ),
[ 'expected' => [ 'exception' => 3,
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => $sBuffer10031 ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: "123-a_B.c"'              , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '123-a_B.c' ),
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => '123-a_B.c' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => true ],
                        ]],
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => $sBuffer10031 . DIRECTORY_SEPARATOR
                                                                                          . '123-a_B.c' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => true ],
                        ]],
//array( 'label'=>'TEST: ../LICENSE'           , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '..'
//                                                                    . DIRECTORY_SEPARATOR . 'LICENSE' ),
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => '..' . DIRECTORY_SEPARATOR . 'LICENSE' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => APPLICATION_PATH . DIRECTORY_SEPARATOR
                                                                                         . 'LICENSE' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => false ],
                        ]],
//array( 'label'=>'TEST: Iñtërnâtiônàlizætiøn.txt' , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . 'Iñtërnâtiônàlizætiøn.txt' ),
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => 'Iñtërnâtiônàlizætiøn.txt' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => true ],
                        ]],
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => $sBuffer10031 . DIRECTORY_SEPARATOR
                                                                                          . 'Iñtërnâtiônàlizætiøn.txt' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => true ],
                        ]],
//array( 'label'=>'TEST: Iñtërnâtiônàlizætiøn'     , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . 'Iñtërnâtiônàlizætiøn' )
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => 'Iñtërnâtiônàlizætiøn' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => true ],
                        ]],
[ 'expected' => [ 'exception' => 0,
                         '__toString' => [ 'exception' => 0, 'return' => $sBuffer10031 . DIRECTORY_SEPARATOR
                                                                                          . 'Iñtërnâtiônàlizætiøn' ],
                    'createDirectory' => [ 'exception' => 0, 'return' => true ],
                        ]],
];
