<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = array(
//array( 'label'=>'TEST: /'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '/' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => $sBuffer10031 ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: \\'                       , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '\\' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => $sBuffer10031 ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: :'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . ':' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: *'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '*' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: ?'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '?' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: "'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '"' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: <'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '<' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: >'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '>' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: |'                        , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '|' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: ""'                       , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '' ),
array( 'expected'=>array( 'exception' => 3,
                         '__toString' => array( 'exception'=>0, 'return' => '' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => $sBuffer10031 ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: "123-a_B.c"'              , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '123-a_B.c' ),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => '123-a_B.c' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => TRUE ),
                        )),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => $sBuffer10031 . DIRECTORY_SEPARATOR
                                                                                          . '123-a_B.c' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => TRUE ),
                        )),
//array( 'label'=>'TEST: ../LICENSE'           , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . '..'
//                                                                    . DIRECTORY_SEPARATOR . 'LICENSE' ),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => '..' . DIRECTORY_SEPARATOR . 'LICENSE' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => APPLICATION_PATH . DIRECTORY_SEPARATOR
                                                                                         . 'LICENSE' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => FALSE ),
                        )),
//array( 'label'=>'TEST: Iñtërnâtiônàlizætiøn.txt' , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . 'Iñtërnâtiônàlizætiøn.txt' ),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => 'Iñtërnâtiônàlizætiøn.txt' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => TRUE ),
                        )),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => $sBuffer10031 . DIRECTORY_SEPARATOR
                                                                                          . 'Iñtërnâtiônàlizætiøn.txt' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => TRUE ),
                        )),
//array( 'label'=>'TEST: Iñtërnâtiônàlizætiøn'     , 'test'=>APPLICATION_PATH . '/data/uploads' . DIRECTORY_SEPARATOR . 'Iñtërnâtiônàlizætiøn' )
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => 'Iñtërnâtiônàlizætiøn' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => TRUE ),
                        )),
array( 'expected'=>array( 'exception' => 0,
                         '__toString' => array( 'exception'=>0, 'return' => $sBuffer10031 . DIRECTORY_SEPARATOR
                                                                                          . 'Iñtërnâtiônàlizætiøn' ),
                    'createDirectory' => array( 'exception'=>0, 'return' => TRUE ),
                        )),
);