<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = [
//array( 'label'=>'TEST: null'          , 'test'=>NULL),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: array'         , 'test'=>array('This','is')),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: array empty'   , 'test'=>array()),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: object'        , 'test'=>(object)array()),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: CFloat'        , 'test'=>new \Foundation\Type\Simple\CFloat(1.234) ),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: CInt'          , 'test'=>new \Foundation\Type\Simple\CInt(123) ),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: CByte'         , 'test'=>new \Foundation\Type\Complex\CByte('16M') ),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: CString'       , 'test'=>new \Foundation\Type\Simple\CString('ceci est une chaîne') ),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: CPath'         , 'test'=>new \Foundation\Type\Complex\CPath('/var/tmp') ),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => true ],
            'getValue'    => [ 'exception' => 0, 'return'    => '/var/tmp' ],
            '__toString'  => [ 'exception' => 0, 'return'    => '/var/tmp' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 8 ],
            'getBasename' => [ 'exception' => 0, 'return'    => 'tmp' ],
            'getRealPath' => [ 'exception' => 0, 'return'    => ( (DIRECTORY_SEPARATOR == '\\') ? false : '/var/tmp') ],
        ] ],
//array( 'label'=>'TEST: CEmailAddress' , 'test'=>new \Foundation\Type\Complex\CEmailAddress('toto@café-frappé.com') ),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: CIp'           , 'test'=>new \Foundation\Type\Complex\CIp('192.168.33.1') ),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: resource'      , 'test'=>new \SplFileObject(__FILE__) ),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
//array( 'label'=>'TEST: CHostname'     , 'test'=>new \Foundation\Type\Complex\CHostname('domain.com') ),
    [ 'expected' => [ 'exception'   => 0,
            'isvalid'     => [ 'exception' => 0, 'return'    => false ],
            'getValue'    => [ 'exception' => 0, 'return'    => null ],
            '__toString'  => [ 'exception' => 0, 'return'    => '' ],
            'getLength'   => [ 'exception' => 0, 'return'    => 0 ],
            'getBasename' => [ 'exception' => 0, 'return'    => null ],
            'getRealPath' => [ 'exception' => 0, 'return'    => false ],
        ] ],
];
