<?php
$this->_aTests[self::KEY_TEST] = array(
    // Other: Format
array( 'label'=>'TEST 001: "­"' , 'test'=>'­'),
    // Other: Control
array( 'label'=>'TEST 101: chr(0x09)' , 'test'=>chr(0x09)),
array( 'label'=>'TEST 102: chr(0x0B)' , 'test'=>chr(0x0B)),
array( 'label'=>'TEST 103: chr(0x0A)' , 'test'=>chr(0x0A)),
array( 'label'=>'TEST 104: chr(0x0D)' , 'test'=>chr(0x0D)),
array( 'label'=>'TEST 105: chr(0x08)' , 'test'=>chr(0x08)),
array( 'label'=>'TEST 106: chr(0x0C)' , 'test'=>chr(0x0C)),
array( 'label'=>'TEST 107: chr(0x07)' , 'test'=>chr(0x07)),
array( 'label'=>'TEST 108: chr(0x1B)' , 'test'=>chr(0x1B)),
    // Ponctuation: Other
array( 'label'=>'TEST 201: "!"' , 'test'=>'!'),
array( 'label'=>'TEST 202: """' , 'test'=>'"'),
array( 'label'=>'TEST 203: "#"' , 'test'=>'#'),
array( 'label'=>'TEST 204: "%"' , 'test'=>'%'),
array( 'label'=>'TEST 205: "&"' , 'test'=>'&'),
array( 'label'=>'TEST 206: "*"' , 'test'=>'*'),
array( 'label'=>'TEST 207: ","' , 'test'=>','),
array( 'label'=>'TEST 208: "/"' , 'test'=>'/'),
array( 'label'=>'TEST 209: ":"' , 'test'=>':'),
array( 'label'=>'TEST 210: ";"' , 'test'=>';'),
array( 'label'=>'TEST 211: "?"' , 'test'=>'?'),
array( 'label'=>'TEST 212: "\\"' , 'test'=>'\\'),
array( 'label'=>'TEST 213: "¡"' , 'test'=>'¡'),
array( 'label'=>'TEST 214: "·"' , 'test'=>'·'),
array( 'label'=>'TEST 215: "¿"' , 'test'=>'¿'),
array( 'label'=>'TEST 216: "\'"' , 'test'=>'\''),
array( 'label'=>'TEST 217: "."' , 'test'=>'.'),
    // Ponctuation: Dash
array( 'label'=>'TEST 301: "-"' , 'test'=>'-'),
    // Ponctuation: Bracket & quote
array( 'label'=>'TEST 401: "("' , 'test'=>'('),
array( 'label'=>'TEST 402: ")"' , 'test'=>')'),
array( 'label'=>'TEST 403: "["' , 'test'=>'['),
array( 'label'=>'TEST 404: "]"' , 'test'=>']'),
array( 'label'=>'TEST 405: "{"' , 'test'=>'{'),
array( 'label'=>'TEST 406: "}"' , 'test'=>'}'),
array( 'label'=>'TEST 407: "«"' , 'test'=>'«'),
array( 'label'=>'TEST 408: "»"' , 'test'=>'»'),
  // Ponctuation: Connector
array( 'label'=>'TEST 501: "_"' , 'test'=>'_'),
    // Number: Other
array( 'label'=>'TEST 601: "²"' , 'test'=>'²'),
array( 'label'=>'TEST 602: "³"' , 'test'=>'³'),
array( 'label'=>'TEST 603: "¹"' , 'test'=>'¹'),
array( 'label'=>'TEST 604: "¼"' , 'test'=>'¼'),
array( 'label'=>'TEST 605: "½"' , 'test'=>'½'),
array( 'label'=>'TEST 606: "¾"' , 'test'=>'¾'),
    // Symbol: Other
array( 'label'=>'TEST 701: "¦"' , 'test'=>'¦'),
array( 'label'=>'TEST 702: "§"' , 'test'=>'§'),
array( 'label'=>'TEST 703: "©"' , 'test'=>'©'),
array( 'label'=>'TEST 704: "®"' , 'test'=>'®'),
array( 'label'=>'TEST 705: "°"' , 'test'=>'°'),
array( 'label'=>'TEST 706: "¶"' , 'test'=>'¶'),
    // Symbol: Modifier
array( 'label'=>'TEST 801: "^"' , 'test'=>'^'),
array( 'label'=>'TEST 802: "`"' , 'test'=>'`'),
array( 'label'=>'TEST 803: "¨"' , 'test'=>'¨'),
array( 'label'=>'TEST 804: "¯"' , 'test'=>'¯'),
array( 'label'=>'TEST 805: "´"' , 'test'=>'´'),
array( 'label'=>'TEST 806: "¸"' , 'test'=>'¸'),
    // Symbol: Currency
array( 'label'=>'TEST 901: "$"' , 'test'=>'$'),
array( 'label'=>'TEST 902: "¢"' , 'test'=>'¢'),
array( 'label'=>'TEST 903: "£"' , 'test'=>'£'),
array( 'label'=>'TEST 904: "¤"' , 'test'=>'¤'),
array( 'label'=>'TEST 905: "¥"' , 'test'=>'¥'),
    // Symbol: Math
array( 'label'=>'TEST 1001: "+"' , 'test'=>'+'),
array( 'label'=>'TEST 1002: "<"' , 'test'=>'<'),
array( 'label'=>'TEST 1003: "="' , 'test'=>'='),
array( 'label'=>'TEST 1004: ">"' , 'test'=>'>'),
array( 'label'=>'TEST 1005: "|"' , 'test'=>'|'),
array( 'label'=>'TEST 1006: "~"' , 'test'=>'~'),
array( 'label'=>'TEST 1007: "¬"' , 'test'=>'¬'),
array( 'label'=>'TEST 1008: "±"' , 'test'=>'±'),
array( 'label'=>'TEST 1009: "×"' , 'test'=>'×'),
array( 'label'=>'TEST 1010: "÷"' , 'test'=>'÷'),
    // Letter: Lowercase
array( 'label'=>'TEST 1101: "ª"' , 'test'=>'ª'),
array( 'label'=>'TEST 1102: "µ"' , 'test'=>'µ'),
array( 'label'=>'TEST 1103: "º"' , 'test'=>'º'),
array( 'label'=>'TEST 1104: "а"' , 'test'=>'а'),
array( 'label'=>'TEST 1105: "б"' , 'test'=>'б'),
array( 'label'=>'TEST 1106: "в"' , 'test'=>'в'),
array( 'label'=>'TEST 1107: "г"' , 'test'=>'г'),
array( 'label'=>'TEST 1108: "д"' , 'test'=>'д'),
array( 'label'=>'TEST 1109: "е"' , 'test'=>'е'),
array( 'label'=>'TEST 1110: "ё"' , 'test'=>'ё'),
array( 'label'=>'TEST 1111: "ж"' , 'test'=>'ж'),
array( 'label'=>'TEST 1112: "з"' , 'test'=>'з'),
array( 'label'=>'TEST 1113: "и"' , 'test'=>'и'),
array( 'label'=>'TEST 1114: "й"' , 'test'=>'й'),
array( 'label'=>'TEST 1115: "к"' , 'test'=>'к'),
array( 'label'=>'TEST 1116: "л"' , 'test'=>'л'),
array( 'label'=>'TEST 1117: "м"' , 'test'=>'м'),
array( 'label'=>'TEST 1118: "н"' , 'test'=>'н'),
array( 'label'=>'TEST 1119: "о"' , 'test'=>'о'),
array( 'label'=>'TEST 1120: "п"' , 'test'=>'п'),
array( 'label'=>'TEST 1121: "р"' , 'test'=>'р'),
array( 'label'=>'TEST 1122: "с"' , 'test'=>'с'),
array( 'label'=>'TEST 1123: "т"' , 'test'=>'т'),
array( 'label'=>'TEST 1124: "у"' , 'test'=>'у'),
array( 'label'=>'TEST 1125: "ф"' , 'test'=>'ф'),
array( 'label'=>'TEST 1126: "х"' , 'test'=>'х'),
array( 'label'=>'TEST 1127: "ц"' , 'test'=>'ц'),
array( 'label'=>'TEST 1128: "ч"' , 'test'=>'ч'),
array( 'label'=>'TEST 1129: "ш"' , 'test'=>'ш'),
array( 'label'=>'TEST 1130: "щ"' , 'test'=>'щ'),
array( 'label'=>'TEST 1131: "э"' , 'test'=>'э'),
array( 'label'=>'TEST 1132: "ю"' , 'test'=>'ю'),
array( 'label'=>'TEST 1133: "я"' , 'test'=>'я'),
array( 'label'=>'TEST 1134: "ъ"' , 'test'=>'ъ'),
array( 'label'=>'TEST 1135: "ы"' , 'test'=>'ы'),
array( 'label'=>'TEST 1136: "ь"' , 'test'=>'ь'),
array( 'label'=>'TEST 1137: "ø"' , 'test'=>'ø'),
array( 'label'=>'TEST 1138: "ù"' , 'test'=>'ù'),
array( 'label'=>'TEST 1139: "ú"' , 'test'=>'ú'),
array( 'label'=>'TEST 1140: "û"' , 'test'=>'û'),
array( 'label'=>'TEST 1141: "ü"' , 'test'=>'ü'),
array( 'label'=>'TEST 1142: "ý"' , 'test'=>'ý'),
array( 'label'=>'TEST 1143: "þ"' , 'test'=>'þ'),
array( 'label'=>'TEST 1144: "ÿ"' , 'test'=>'ÿ'),
array( 'label'=>'TEST 1145: "ß"' , 'test'=>'ß'),
array( 'label'=>'TEST 1146: "à"' , 'test'=>'à'),
array( 'label'=>'TEST 1147: "á"' , 'test'=>'á'),
array( 'label'=>'TEST 1148: "â"' , 'test'=>'â'),
array( 'label'=>'TEST 1149: "ã"' , 'test'=>'ã'),
array( 'label'=>'TEST 1150: "ä"' , 'test'=>'ä'),
array( 'label'=>'TEST 1151: "å"' , 'test'=>'å'),
array( 'label'=>'TEST 1152: "æ"' , 'test'=>'æ'),
array( 'label'=>'TEST 1153: "ç"' , 'test'=>'ç'),
array( 'label'=>'TEST 1154: "è"' , 'test'=>'è'),
array( 'label'=>'TEST 1155: "é"' , 'test'=>'é'),
array( 'label'=>'TEST 1156: "ê"' , 'test'=>'ê'),
array( 'label'=>'TEST 1157: "ë"' , 'test'=>'ë'),
array( 'label'=>'TEST 1158: "ì"' , 'test'=>'ì'),
array( 'label'=>'TEST 1159: "í"' , 'test'=>'í'),
array( 'label'=>'TEST 1160: "î"' , 'test'=>'î'),
array( 'label'=>'TEST 1161: "ï"' , 'test'=>'ï'),
array( 'label'=>'TEST 1162: "ð"' , 'test'=>'ð'),
array( 'label'=>'TEST 1163: "ñ"' , 'test'=>'ñ'),
array( 'label'=>'TEST 1164: "ò"' , 'test'=>'ò'),
array( 'label'=>'TEST 1165: "ó"' , 'test'=>'ó'),
array( 'label'=>'TEST 1166: "ô"' , 'test'=>'ô'),
array( 'label'=>'TEST 1167: "õ"' , 'test'=>'õ'),
array( 'label'=>'TEST 1168: "ö"' , 'test'=>'ö'),
//     Letter: Uppercase
array( 'label'=>'TEST: "А"' , 'test'=>'А'),
array( 'label'=>'TEST: "Б"' , 'test'=>'Б'),
array( 'label'=>'TEST: "В"' , 'test'=>'В'),
array( 'label'=>'TEST: "Г"' , 'test'=>'Г'),
array( 'label'=>'TEST: "Д"' , 'test'=>'Д'),
array( 'label'=>'TEST: "Е"' , 'test'=>'Е'),
array( 'label'=>'TEST: "Ё"' , 'test'=>'Ё'),
array( 'label'=>'TEST: "Ж"' , 'test'=>'Ж'),
array( 'label'=>'TEST: "З"' , 'test'=>'З'),
array( 'label'=>'TEST: "И"' , 'test'=>'И'),
array( 'label'=>'TEST: "Й"' , 'test'=>'Й'),
array( 'label'=>'TEST: "К"' , 'test'=>'К'),
array( 'label'=>'TEST: "Л"' , 'test'=>'Л'),
array( 'label'=>'TEST: "М"' , 'test'=>'М'),
array( 'label'=>'TEST: "Н"' , 'test'=>'Н'),
array( 'label'=>'TEST: "О"' , 'test'=>'О'),
array( 'label'=>'TEST: "П"' , 'test'=>'П'),
array( 'label'=>'TEST: "Р"' , 'test'=>'Р'),
array( 'label'=>'TEST: "С"' , 'test'=>'С'),
array( 'label'=>'TEST: "Т"' , 'test'=>'Т'),
array( 'label'=>'TEST: "У"' , 'test'=>'У'),
array( 'label'=>'TEST: "Ф"' , 'test'=>'Ф'),
array( 'label'=>'TEST: "Х"' , 'test'=>'Х'),
array( 'label'=>'TEST: "Ц"' , 'test'=>'Ц'),
array( 'label'=>'TEST: "Ч"' , 'test'=>'Ч'),
array( 'label'=>'TEST: "Ш"' , 'test'=>'Ш'),
array( 'label'=>'TEST: "Щ"' , 'test'=>'Щ'),
array( 'label'=>'TEST: "Э"' , 'test'=>'Э'),
array( 'label'=>'TEST: "Ю"' , 'test'=>'Ю'),
array( 'label'=>'TEST: "Я"' , 'test'=>'Я'),
array( 'label'=>'TEST: "Ъ"' , 'test'=>'Ъ'),
array( 'label'=>'TEST: "Ы"' , 'test'=>'Ы'),
array( 'label'=>'TEST: "Ь"' , 'test'=>'Ь'),
array( 'label'=>'TEST: "À"' , 'test'=>'À'),
array( 'label'=>'TEST: "Á"' , 'test'=>'Á'),
array( 'label'=>'TEST: "Â"' , 'test'=>'Â'),
array( 'label'=>'TEST: "Ã"' , 'test'=>'Ã'),
array( 'label'=>'TEST: "Ä"' , 'test'=>'Ä'),
array( 'label'=>'TEST: "Å"' , 'test'=>'Å'),
array( 'label'=>'TEST: "Æ"' , 'test'=>'Æ'),
array( 'label'=>'TEST: "Ç"' , 'test'=>'Ç'),
array( 'label'=>'TEST: "È"' , 'test'=>'È'),
array( 'label'=>'TEST: "É"' , 'test'=>'É'),
array( 'label'=>'TEST: "Ê"' , 'test'=>'Ê'),
array( 'label'=>'TEST: "Ë"' , 'test'=>'Ë'),
array( 'label'=>'TEST: "Ì"' , 'test'=>'Ì'),
array( 'label'=>'TEST: "Í"' , 'test'=>'Í'),
array( 'label'=>'TEST: "Î"' , 'test'=>'Î'),
array( 'label'=>'TEST: "Ï"' , 'test'=>'Ï'),
array( 'label'=>'TEST: "Ð"' , 'test'=>'Ð'),
array( 'label'=>'TEST: "Ñ"' , 'test'=>'Ñ'),
array( 'label'=>'TEST: "Ò"' , 'test'=>'Ò'),
array( 'label'=>'TEST: "Ó"' , 'test'=>'Ó'),
array( 'label'=>'TEST: "Ô"' , 'test'=>'Ô'),
array( 'label'=>'TEST: "Õ"' , 'test'=>'Õ'),
array( 'label'=>'TEST: "Ö"' , 'test'=>'Ö'),
array( 'label'=>'TEST: "Ø"' , 'test'=>'Ø'),
array( 'label'=>'TEST: "Ù"' , 'test'=>'Ù'),
array( 'label'=>'TEST: "Ú"' , 'test'=>'Ú'),
array( 'label'=>'TEST: "Û"' , 'test'=>'Û'),
array( 'label'=>'TEST: "Ü"' , 'test'=>'Ü'),
array( 'label'=>'TEST: "Ý"' , 'test'=>'Ý'),
array( 'label'=>'TEST: "Þ"' , 'test'=>'Þ'),
);