<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Foundation\Cache\CAntiFlood'               => __DIR__ . '/Cache/CAntiFlood.php',
    'Foundation\Cache\Storage\CApc'             => __DIR__ . '/Cache/Storage/CApc.php',
    'Foundation\Cache\Storage\CArray'           => __DIR__ . '/Cache/Storage/CArray.php',
    'Foundation\Cache\Storage\CStorageAbstract' => __DIR__ . '/Cache/Storage/CStorageAbstract.php',
    'Foundation\Cache\Storage\StorageInterface' => __DIR__ . '/Cache/Storage/StorageInterface.php',
);
