<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Foundation\Debug\Benchmark\CBenchmark'   => __DIR__ . '/Debug/Benchmark/CBenchmark.php',
    'Foundation\Debug\Benchmark\CMeasure'     => __DIR__ . '/Debug/Benchmark/CMeasure.php',
    'Foundation\Debug\CDebugger'              => __DIR__ . '/Debug/CDebugger.php',
    'Foundation\Debug\CTracer'                => __DIR__ . '/Debug/CTracer.php',
    'Foundation\Debug\Memory\CCore'           => __DIR__ . '/Debug/Memory/CCore.php',
    'Foundation\Debug\Memory\CMemorizer'      => __DIR__ . '/Debug/Memory/CMemorizer.php',
    'Foundation\Debug\Memory\CXDebug'         => __DIR__ . '/Debug/Memory/CXDebug.php',
    'Foundation\Debug\Memory\MemoryInterface' => __DIR__ . '/Debug/Memory/MemoryInterface.php',
    'Foundation\Debug\Render\CGoogleChart'    => __DIR__ . '/Debug/Render/CGoogleChart.php',
    'Foundation\Debug\Render\CHtml'           => __DIR__ . '/Debug/Render/CHtml.php',
    'Foundation\Debug\Render\CHtmlFoundation' => __DIR__ . '/Debug/Render/CHtmlFoundation.php',
    'Foundation\Debug\Render\CRenderAbstract' => __DIR__ . '/Debug/Render/CRenderAbstract.php',
    'Foundation\Debug\Render\RenderInterface' => __DIR__ . '/Debug/Render/RenderInterface.php',
    'Foundation\Debug\Timer\CCore'            => __DIR__ . '/Debug/Timer/CCore.php',
    'Foundation\Debug\Timer\CXDebug'          => __DIR__ . '/Debug/Timer/CXDebug.php',
    'Foundation\Debug\Timer\TimerInterface'   => __DIR__ . '/Debug/Timer/TimerInterface.php',
    'Foundation\Debug\Variable\CContainer'    => __DIR__ . '/Debug/Variable/CContainer.php',
];
