<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Foundation\Exception\BadFunctionCallException' => __DIR__ . '/Exception/BadFunctionCallException.php',
    'Foundation\Exception\BadMethodCallException'   => __DIR__ . '/Exception/BadMethodCallException.php',
    'Foundation\Exception\DomainException'          => __DIR__ . '/Exception/DomainException.php',
    'Foundation\Exception\ExceptionInterface'       => __DIR__ . '/Exception/ExceptionInterface.php',
    'Foundation\Exception\InvalidArgumentException' => __DIR__ . '/Exception/InvalidArgumentException.php',
    'Foundation\Exception\LengthException'          => __DIR__ . '/Exception/LengthException.php',
    'Foundation\Exception\OutOfBoundsException'     => __DIR__ . '/Exception/OutOfBoundsException.php',
    'Foundation\Exception\OutOfRangeException'      => __DIR__ . '/Exception/OutOfRangeException.php',
    'Foundation\Exception\OverflowException'        => __DIR__ . '/Exception/OverflowException.php',
    'Foundation\Exception\RangeException'           => __DIR__ . '/Exception/RangeException.php',
    'Foundation\Exception\RuntimeException'         => __DIR__ . '/Exception/RuntimeException.php',
    'Foundation\Exception\UnderflowException'       => __DIR__ . '/Exception/UnderflowException.php',
    'Foundation\Exception\UnexpectedValueException' => __DIR__ . '/Exception/UnexpectedValueException.php',
];
