<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Foundation\Form\CValidatorAbstract' => __DIR__ . '/Form/CValidatorAbstract.php',
    'Foundation\Form\ValidatorInterface' => __DIR__ . '/Form/ValidatorInterface.php',
];
