<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Foundation\Gd\CColor'       => __DIR__ . '/Gd/CColor.php',
    'Foundation\Gd\CCoordinates' => __DIR__ . '/Gd/CCoordinates.php',
    'Foundation\Gd\CDimensions'  => __DIR__ . '/Gd/CDimensions.php',
    'Foundation\Gd\CGDAbstract'  => __DIR__ . '/Gd/CGDAbstract.php',
    'Foundation\Gd\CImage'       => __DIR__ . '/Gd/CImage.php',
    'Foundation\Gd\CResource'    => __DIR__ . '/Gd/CResource.php',
];
