<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Foundation\Loader\CClassMapLoader' => __DIR__ . '/Loader/CClassMapLoader.php',
    'Foundation\Loader\LoaderInterface' => __DIR__ . '/Loader/LoaderInterface.php',
];
