<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Foundation\Log\CLogger'                => __DIR__ . '/Log/CLogger.php',
    'Foundation\Log\CMessage'               => __DIR__ . '/Log/CMessage.php',
    'Foundation\Log\Writer\CFile'           => __DIR__ . '/Log/Writer/CFile.php',
    'Foundation\Log\Writer\CNull'           => __DIR__ . '/Log/Writer/CNull.php',
    'Foundation\Log\Writer\CWriterAbstract' => __DIR__ . '/Log/Writer/CWriterAbstract.php',
    'Foundation\Log\Writer\WriterInterface' => __DIR__ . '/Log/Writer/WriterInterface.php',
);
