<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Foundation\Protocol\CRemoteAddress'                          => __DIR__ . '/Protocol/CRemoteAddress.php',
    'Foundation\Protocol\Connector\CConnectorAbstract'            => __DIR__ . '/Protocol/Connector/CConnectorAbstract.php',
    'Foundation\Protocol\Connector\CCurl'                         => __DIR__ . '/Protocol/Connector/CCurl.php',
    'Foundation\Protocol\Connector\CFile'                         => __DIR__ . '/Protocol/Connector/CFile.php',
    'Foundation\Protocol\Connector\ConnectorInterface'            => __DIR__ . '/Protocol/Connector/ConnectorInterface.php',
    'Foundation\Protocol\Download\Attachment\CAttachmentAbstract' => __DIR__ . '/Protocol/Download/Attachment/CAttachmentAbstract.php',
    'Foundation\Protocol\Download\Attachment\CAudio'              => __DIR__ . '/Protocol/Download/Attachment/CAudio.php',
    'Foundation\Protocol\Download\Attachment\CImage'              => __DIR__ . '/Protocol/Download/Attachment/CImage.php',
    'Foundation\Protocol\Download\CManager'                       => __DIR__ . '/Protocol/Download/CManager.php',
    'Foundation\Protocol\Download\ManagerInterface'               => __DIR__ . '/Protocol/Download/ManagerInterface.php',
);
