<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Foundation\Session\CCsrf'                    => __DIR__ . '/Session/CCsrf.php',
    'Foundation\Session\CSecureSession'           => __DIR__ . '/Session/CSecureSession.php',
    'Foundation\Session\Config\CCookie'           => __DIR__ . '/Session/Config/CCookie.php',
    'Foundation\Session\Storage\CArray'           => __DIR__ . '/Session/Storage/CArray.php',
    'Foundation\Session\Storage\CSession'         => __DIR__ . '/Session/Storage/CSession.php',
    'Foundation\Session\Storage\StorageInterface' => __DIR__ . '/Session/Storage/StorageInterface.php',
];
