<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Foundation\Type\CTypeAbstract'         => __DIR__ . '/Type/CTypeAbstract.php',
    'Foundation\Type\Complex\CByte'         => __DIR__ . '/Type/Complex/CByte.php',
    'Foundation\Type\Complex\CEmailAddress' => __DIR__ . '/Type/Complex/CEmailAddress.php',
    'Foundation\Type\Complex\CHostname'     => __DIR__ . '/Type/Complex/CHostname.php',
    'Foundation\Type\Complex\CIp'           => __DIR__ . '/Type/Complex/CIp.php',
    'Foundation\Type\Complex\CPath'         => __DIR__ . '/Type/Complex/CPath.php',
    'Foundation\Type\Enum\CSeverity'        => __DIR__ . '/Type/Enum/CSeverity.php',
    'Foundation\Type\Simple\CFloat'         => __DIR__ . '/Type/Simple/CFloat.php',
    'Foundation\Type\Simple\CInt'           => __DIR__ . '/Type/Simple/CInt.php',
    'Foundation\Type\Simple\CString'        => __DIR__ . '/Type/Simple/CString.php',
    'Foundation\Type\TypeInterface'         => __DIR__ . '/Type/TypeInterface.php',
);
