<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Foundation\Weather\CReader'                    => __DIR__ . '/Weather/CReader.php',
    'Foundation\Weather\CSpeed'                     => __DIR__ . '/Weather/CSpeed.php',
    'Foundation\Weather\Decoder\CDecoder'           => __DIR__ . '/Weather/Decoder/CDecoder.php',
    'Foundation\Weather\Decoder\CDecoderAbstract'   => __DIR__ . '/Weather/Decoder/CDecoderAbstract.php',
    'Foundation\Weather\Decoder\CDecoderWu'         => __DIR__ . '/Weather/Decoder/CDecoderWu.php',
    'Foundation\Weather\Decoder\CDecoratorAbstract' => __DIR__ . '/Weather/Decoder/CDecoratorAbstract.php',
    'Foundation\Weather\Decoder\DecoderInterface'   => __DIR__ . '/Weather/Decoder/DecoderInterface.php',
    'Foundation\Weather\Reader\ReaderInterface'     => __DIR__ . '/Weather/ReaderInterface.php',
    'YRComms'                                       => __DIR__ . '/Weather/Decoder/yr.php',
    'YRDisplay'                                     => __DIR__ . '/Weather/Decoder/yr.php',
];
