<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = array(
// DNS VALID
// TEST: example.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'example.com',
                '__toString'     => 'example.com',
                'getLength'      => 11,
                'getPunycode'    => 'example.com' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'example.com',
                '__toString'        => 'example.com',
                'getLength'         => 11,
                'getPunycode'       => 'example.com' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array( 'isvalid'        => TRUE,
                'getValue'       => 'example.com',
                '__toString'     => 'example.com',
                'getLength'      => 11,
                'getPunycode'    => 'example.com' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'example.com',
                '__toString'  => 'example.com',
                'getLength'   => 11,
                'getPunycode' => 'example.com' ) ),
    ),
// TEST: example.museum
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'example.museum',
                '__toString'     => 'example.museum',
                'getLength'      => 14,
                'getPunycode'    => 'example.museum' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'example.museum',
                '__toString'        => 'example.museum',
                'getLength'         => 14,
                'getPunycode'       => 'example.museum' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array( 'isvalid'        => TRUE,
                'getValue'       => 'example.museum',
                '__toString'     => 'example.museum',
                'getLength'      => 14,
                'getPunycode'    => 'example.museum' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'example.museum',
                '__toString'  => 'example.museum',
                'getLength'   => 14,
                'getPunycode' => 'example.museum' ) ),
    ),
// TEST: d.hatena.ne.jp
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'd.hatena.ne.jp',
                '__toString'     => 'd.hatena.ne.jp',
                'getLength'      => 14,
                'getPunycode'    => 'd.hatena.ne.jp' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'd.hatena.ne.jp',
                '__toString'        => 'd.hatena.ne.jp',
                'getLength'         => 14,
                'getPunycode'       => 'd.hatena.ne.jp' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array( 'isvalid'        => TRUE,
                'getValue'       => 'd.hatena.ne.jp',
                '__toString'     => 'd.hatena.ne.jp',
                'getLength'      => 14,
                'getPunycode'    => 'd.hatena.ne.jp' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'd.hatena.ne.jp',
                '__toString'  => 'd.hatena.ne.jp',
                'getLength'   => 14,
                'getPunycode' => 'd.hatena.ne.jp' ) ),
    ),
// TEST: 123example.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '123example.com',
                '__toString'     => '123example.com',
                'getLength'      => 14,
                'getPunycode'    => '123example.com' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => '123example.com',
                '__toString'        => '123example.com',
                'getLength'         => 14,
                'getPunycode'       => '123example.com' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array( 'isvalid'        => TRUE,
                'getValue'       => '123example.com',
                '__toString'     => '123example.com',
                'getLength'      => 14,
                'getPunycode'    => '123example.com' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => '123example.com',
                '__toString'  => '123example.com',
                'getLength'   => 14,
                'getPunycode' => '123example.com' ) ),
    ),
// TEST: 1and1.fr
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '1and1.fr',
                '__toString'     => '1and1.fr',
                'getLength'      => 8,
                'getPunycode'    => '1and1.fr' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => '1and1.fr',
                '__toString'        => '1and1.fr',
                'getLength'         => 8,
                'getPunycode'       => '1and1.fr' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '1and1.fr',
                '__toString'     => '1and1.fr',
                'getLength'      => 8,
                'getPunycode'    => '1and1.fr' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => '1and1.fr',
                '__toString'  => '1and1.fr',
                'getLength'   => 8,
                'getPunycode' => '1and1.fr' ) ),
    ),
// TEST: doma-in.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'doma-in.com',
                '__toString'     => 'doma-in.com',
                'getLength'      => 11,
                'getPunycode'    => 'doma-in.com' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'doma-in.com',
                '__toString'        => 'doma-in.com',
                'getLength'         => 11,
                'getPunycode'       => 'doma-in.com' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array( 'isvalid'        => TRUE,
                'getValue'       => 'doma-in.com',
                '__toString'     => 'doma-in.com',
                'getLength'      => 11,
                'getPunycode'    => 'doma-in.com' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'doma-in.com',
                '__toString'  => 'doma-in.com',
                'getLength'   => 11,
                'getPunycode' => 'doma-in.com' ) ),
    ),
// TEST: domain.co.uk
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'domain.co.uk',
                '__toString'     => 'domain.co.uk',
                'getLength'      => 12,
                'getPunycode'    => 'domain.co.uk' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'domain.co.uk',
                '__toString'        => 'domain.co.uk',
                'getLength'         => 12,
                'getPunycode'       => 'domain.co.uk' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'domain.co.uk',
                '__toString'     => 'domain.co.uk',
                'getLength'      => 12,
                'getPunycode'    => 'domain.co.uk' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'domain.co.uk',
                '__toString'  => 'domain.co.uk',
                'getLength'   => 12,
                'getPunycode' => 'domain.co.uk' ) ),
    ),
// DNS NOT VALID
// TEST: example..
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: example..com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: example,com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: exam_ple.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: .example.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: -domain.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: domain-.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: do--main.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: yah&oo.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: y*ahoo.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: ya#hoo
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: test.com / http://www.test.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: ~ex%20ample
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: §bad
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: don?t.know
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TLD
// TEST: www.danger1com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'www.danger1com',
                '__toString'     => 'www.danger1com',
                'getLength'      => 14,
                'getPunycode'    => 'www.danger1com' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'www.danger1com',
                '__toString'        => 'www.danger1com',
                'getLength'         => 14,
                'getPunycode'       => 'www.danger1com' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'www.danger1com',
                '__toString'     => 'www.danger1com',
                'getLength'      => 14,
                'getPunycode'    => 'www.danger1com' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'www.danger1com',
                '__toString'  => 'www.danger1com',
                'getLength'   => 14,
                'getPunycode' => 'www.danger1com' ) ),
    ),
// TEST: dangercom
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'dangercom',
                '__toString'        => 'dangercom',
                'getLength'         => 9,
                'getPunycode'       => 'dangercom' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'dangercom',
                '__toString'  => 'dangercom',
                'getLength'   => 9,
                'getPunycode' => 'dangercom' ) ),
    ),
// TEST: www.dangercom
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'www.dangercom',
                '__toString'     => 'www.dangercom',
                'getLength'      => 13,
                'getPunycode'    => 'www.dangercom' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'www.dangercom',
                '__toString'        => 'www.dangercom',
                'getLength'         => 13,
                'getPunycode'       => 'www.dangercom' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'www.dangercom',
                '__toString'     => 'www.dangercom',
                'getLength'      => 13,
                'getPunycode'    => 'www.dangercom' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'www.dangercom',
                '__toString'  => 'www.dangercom',
                'getLength'   => 13,
                'getPunycode' => 'www.dangercom' ) ),
    ),
// TEST: example.f1
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'example.f1',
                '__toString'     => 'example.f1',
                'getLength'      => 10,
                'getPunycode'    => 'example.f1' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'example.f1',
                '__toString'        => 'example.f1',
                'getLength'         => 10,
                'getPunycode'       => 'example.f1' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'example.f1',
                '__toString'     => 'example.f1',
                'getLength'      => 10,
                'getPunycode'    => 'example.f1' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'example.f1',
                '__toString'  => 'example.f1',
                'getLength'   => 10,
                'getPunycode' => 'example.f1' ) ),
    ),
// TEST: example.f-r
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'example.f-r',
                '__toString'     => 'example.f-r',
                'getLength'      => 11,
                'getPunycode'    => 'example.f-r' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'example.f-r',
                '__toString'        => 'example.f-r',
                'getLength'         => 11,
                'getPunycode'       => 'example.f-r' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'example.f-r',
                '__toString'     => 'example.f-r',
                'getLength'      => 11,
                'getPunycode'    => 'example.f-r' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'example.f-r',
                '__toString'  => 'example.f-r',
                'getLength'   => 11,
                'getPunycode' => 'example.f-r' ) ),
    ),
// TLD NOT VALID
// TEST: example.c
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ) ),
    ),
// TEST: example.123
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ) ),
    ),
// TEST: example.-fr
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: example.fr-
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// LOCAL VALID
// TEST: localhost
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'localhost',
                '__toString'        => 'localhost',
                'getLength'         => 9,
                'getPunycode'       => 'localhost' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'localhost',
                '__toString'  => 'localhost',
                'getLength'   => 9,
                'getPunycode' => 'localhost' ) ),
    ),
// TEST: localhost.localdomain
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'localhost.localdomain',
                '__toString'     => 'localhost.localdomain',
                'getLength'      => 21,
                'getPunycode'    => 'localhost.localdomain' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'localhost.localdomain',
                '__toString'        => 'localhost.localdomain',
                'getLength'         => 21,
                'getPunycode'       => 'localhost.localdomain' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'localhost.localdomain',
                '__toString'     => 'localhost.localdomain',
                'getLength'      => 21,
                'getPunycode'    => 'localhost.localdomain' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'localhost.localdomain',
                '__toString'  => 'localhost.localdomain',
                'getLength'   => 21,
                'getPunycode' => 'localhost.localdomain' ) ),
    ),
// LOCAL NOT VALID
// TEST: local host
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: .localhost
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// PUNYCODE NOT VALID
// TEST: xn--brger-x45d2va.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: xn--bürger.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: xn--
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// PARTIAL
// TEST: example.
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: example.com.
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// TEST: ~ex%20ample.
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'     => FALSE,
                'getValue'    => NULL,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => NULL ) ),
    ),
// IDN VALID
// TEST: café-glacé.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'café-glacé.com',
                '__toString'     => 'café-glacé.com',
                'getLength'      => 14,
                'getPunycode'    => 'xn--caf-glac-d1af.com' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'café-glacé.com',
                '__toString'        => 'café-glacé.com',
                'getLength'         => 14,
                'getPunycode'       => 'xn--caf-glac-d1af.com' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'café-glacé.com',
                '__toString'     => 'café-glacé.com',
                'getLength'      => 14,
                'getPunycode'    => 'xn--caf-glac-d1af.com' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'café-glacé.com',
                '__toString'  => 'café-glacé.com',
                'getLength'   => 14,
                'getPunycode' => 'xn--caf-glac-d1af.com' ) ),
    ),
// TEST: café.glacé.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'café.glacé.com',
                '__toString'     => 'café.glacé.com',
                'getLength'      => 14,
                'getPunycode'    => 'xn--caf-dma.xn--glac-epa.com' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'café.glacé.com',
                '__toString'        => 'café.glacé.com',
                'getLength'         => 14,
                'getPunycode'       => 'xn--caf-dma.xn--glac-epa.com' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'café.glacé.com',
                '__toString'     => 'café.glacé.com',
                'getLength'      => 14,
                'getPunycode'    => 'xn--caf-dma.xn--glac-epa.com' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'café.glacé.com',
                '__toString'  => 'café.glacé.com',
                'getLength'   => 14,
                'getPunycode' => 'xn--caf-dma.xn--glac-epa.com' ) ),
    ),
// TEST: 1café.glacé2.com
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '1café.glacé2.com',
                '__toString'     => '1café.glacé2.com',
                'getLength'      => 16,
                'getPunycode'    => 'xn--1caf-epa.xn--glac2-esa.com' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => '1café.glacé2.com',
                '__toString'        => '1café.glacé2.com',
                'getLength'         => 16,
                'getPunycode'       => 'xn--1caf-epa.xn--glac2-esa.com' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '1café.glacé2.com',
                '__toString'     => '1café.glacé2.com',
                'getLength'      => 16,
                'getPunycode'    => 'xn--1caf-epa.xn--glac2-esa.com' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => '1café.glacé2.com',
                '__toString'  => '1café.glacé2.com',
                'getLength'   => 16,
                'getPunycode' => 'xn--1caf-epa.xn--glac2-esa.com' ) ),
    ),
// TEST: 上海世博会.中国
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '上海世博会.中国',
                '__toString'     => '上海世博会.中国',
                'getLength'      => 8,
                'getPunycode'    => 'xn--fhqya62el8j7s3b.xn--fiqs8s' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => '上海世博会.中国',
                '__toString'        => '上海世博会.中国',
                'getLength'         => 8,
                'getPunycode'       => 'xn--fhqya62el8j7s3b.xn--fiqs8s' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '上海世博会.中国',
                '__toString'     => '上海世博会.中国',
                'getLength'      => 8,
                'getPunycode'    => 'xn--fhqya62el8j7s3b.xn--fiqs8s' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => '上海世博会.中国',
                '__toString'  => '上海世博会.中国',
                'getLength'   => 8,
                'getPunycode' => 'xn--fhqya62el8j7s3b.xn--fiqs8s' ) ),
    ),
// TEST: Latin supernovæ.fr
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'supernovæ.fr',
                '__toString'     => 'supernovæ.fr',
                'getLength'      => 12,
                'getPunycode'    => 'xn--supernov-q0a.fr' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'supernovæ.fr',
                '__toString'        => 'supernovæ.fr',
                'getLength'         => 12,
                'getPunycode'       => 'xn--supernov-q0a.fr' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'supernovæ.fr',
                '__toString'     => 'supernovæ.fr',
                'getLength'      => 12,
                'getPunycode'    => 'xn--supernov-q0a.fr' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'supernovæ.fr',
                '__toString'  => 'supernovæ.fr',
                'getLength'   => 12,
                'getPunycode' => 'xn--supernov-q0a.fr' ) ),
    ),
// TEST: Arabic مثال.إختبار
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'مثال.إختبار',
                '__toString'     => 'مثال.إختبار',
                'getLength'      => 11,
                'getPunycode'    => 'xn--mgbh0fb.xn--kgbechtv' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'مثال.إختبار',
                '__toString'        => 'مثال.إختبار',
                'getLength'         => 11,
                'getPunycode'       => 'xn--mgbh0fb.xn--kgbechtv' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'مثال.إختبار',
                '__toString'     => 'مثال.إختبار',
                'getLength'      => 11,
                'getPunycode'    => 'xn--mgbh0fb.xn--kgbechtv' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'مثال.إختبار',
                '__toString'  => 'مثال.إختبار',
                'getLength'   => 11,
                'getPunycode' => 'xn--mgbh0fb.xn--kgbechtv' ) ),
    ),
// TEST: Simplified Chinese 例子.测试
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '例子.测试',
                '__toString'     => '例子.测试',
                'getLength'      => 5,
                'getPunycode'    => 'xn--fsqu00a.xn--0zwm56d' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => '例子.测试',
                '__toString'        => '例子.测试',
                'getLength'         => 5,
                'getPunycode'       => 'xn--fsqu00a.xn--0zwm56d' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '例子.测试',
                '__toString'     => '例子.测试',
                'getLength'      => 5,
                'getPunycode'    => 'xn--fsqu00a.xn--0zwm56d' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => '例子.测试',
                '__toString'  => '例子.测试',
                'getLength'   => 5,
                'getPunycode' => 'xn--fsqu00a.xn--0zwm56d' ) ),
    ),
// TEST: Traditional Chinese 例子.測試
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '例子.測試',
                '__toString'     => '例子.測試',
                'getLength'      => 5,
                'getPunycode'    => 'xn--fsqu00a.xn--g6w251d' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => '例子.測試',
                '__toString'        => '例子.測試',
                'getLength'         => 5,
                'getPunycode'       => 'xn--fsqu00a.xn--g6w251d' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '例子.測試',
                '__toString'     => '例子.測試',
                'getLength'      => 5,
                'getPunycode'    => 'xn--fsqu00a.xn--g6w251d' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => '例子.測試',
                '__toString'  => '例子.測試',
                'getLength'   => 5,
                'getPunycode' => 'xn--fsqu00a.xn--g6w251d' ) ),
    ),
// TEST: Greek παράδειγμα.δοκιμή
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'παράδειγμα.δοκιμή',
                '__toString'     => 'παράδειγμα.δοκιμή',
                'getLength'      => 17,
                'getPunycode'    => 'xn--hxajbheg2az3al.xn--jxalpdlp' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'παράδειγμα.δοκιμή',
                '__toString'        => 'παράδειγμα.δοκιμή',
                'getLength'         => 17,
                'getPunycode'       => 'xn--hxajbheg2az3al.xn--jxalpdlp' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'παράδειγμα.δοκιμή',
                '__toString'     => 'παράδειγμα.δοκιμή',
                'getLength'      => 17,
                'getPunycode'    => 'xn--hxajbheg2az3al.xn--jxalpdlp' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'παράδειγμα.δοκιμή',
                '__toString'  => 'παράδειγμα.δοκιμή',
                'getLength'   => 17,
                'getPunycode' => 'xn--hxajbheg2az3al.xn--jxalpdlp' ) ),
    ),
// TEST: Devanagari Hindi उदाहरण.परीक्षा
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'उदाहरण.परीक्षा',
                '__toString'     => 'उदाहरण.परीक्षा',
                'getLength'      => 14,
                'getPunycode'    => 'xn--p1b6ci4b4b3a.xn--11b5bs3a9aj6g' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'उदाहरण.परीक्षा',
                '__toString'  => 'उदाहरण.परीक्षा',
                'getLength'   => 14,
                'getPunycode' => 'xn--p1b6ci4b4b3a.xn--11b5bs3a9aj6g' ) ),
    ),
// TEST: Kanji, Hiragana, Katakana Japanese 例え.テスト
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '例え.テスト',
                '__toString'     => '例え.テスト',
                'getLength'      => 6,
                'getPunycode'    => 'xn--r8jz45g.xn--zckzah' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => '例え.テスト',
                '__toString'        => '例え.テスト',
                'getLength'         => 6,
                'getPunycode'       => 'xn--r8jz45g.xn--zckzah' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '例え.テスト',
                '__toString'     => '例え.テスト',
                'getLength'      => 6,
                'getPunycode'    => 'xn--r8jz45g.xn--zckzah' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => '例え.テスト',
                '__toString'  => '例え.テスト',
                'getLength'   => 6,
                'getPunycode' => 'xn--r8jz45g.xn--zckzah' ) ),
    ),
// TEST: Hangul Korean 실례.테스트
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '실례.테스트',
                '__toString'     => '실례.테스트',
                'getLength'      => 6,
                'getPunycode'    => 'xn--9n2bp8q.xn--9t4b11yi5a' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => '실례.테스트',
                '__toString'        => '실례.테스트',
                'getLength'         => 6,
                'getPunycode'       => 'xn--9n2bp8q.xn--9t4b11yi5a' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => '실례.테스트',
                '__toString'     => '실례.테스트',
                'getLength'      => 6,
                'getPunycode'    => 'xn--9n2bp8q.xn--9t4b11yi5a' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => '실례.테스트',
                '__toString'  => '실례.테스트',
                'getLength'   => 6,
                'getPunycode' => 'xn--9n2bp8q.xn--9t4b11yi5a' ) ),
    ),
// TEST: Perso-Arabic مثال.آزمایشی
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'مثال.آزمایشی',
                '__toString'     => 'مثال.آزمایشی',
                'getLength'      => 12,
                'getPunycode'    => 'xn--mgbh0fb.xn--hgbk6aj7f53bba' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'مثال.آزمایشی',
                '__toString'        => 'مثال.آزمایشی',
                'getLength'         => 12,
                'getPunycode'       => 'xn--mgbh0fb.xn--hgbk6aj7f53bba' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'مثال.آزمایشی',
                '__toString'     => 'مثال.آزمایشی',
                'getLength'      => 12,
                'getPunycode'    => 'xn--mgbh0fb.xn--hgbk6aj7f53bba' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'مثال.آزمایشی',
                '__toString'  => 'مثال.آزمایشی',
                'getLength'   => 12,
                'getPunycode' => 'xn--mgbh0fb.xn--hgbk6aj7f53bba' ) ),
    ),
// TEST: Cyrillic Russian пример.испытание
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'пример.испытание',
                '__toString'     => 'пример.испытание',
                'getLength'      => 16,
                'getPunycode'    => 'xn--e1afmkfd.xn--80akhbyknj4f' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'пример.испытание',
                '__toString'        => 'пример.испытание',
                'getLength'         => 16,
                'getPunycode'       => 'xn--e1afmkfd.xn--80akhbyknj4f' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'пример.испытание',
                '__toString'     => 'пример.испытание',
                'getLength'      => 16,
                'getPunycode'    => 'xn--e1afmkfd.xn--80akhbyknj4f' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'пример.испытание',
                '__toString'  => 'пример.испытание',
                'getLength'   => 16,
                'getPunycode' => 'xn--e1afmkfd.xn--80akhbyknj4f' ) ),
    ),
// TEST: Tamil உதாரணம்.பரிட்சை
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'உதாரணம்.பரிட்சை',
                '__toString'     => 'உதாரணம்.பரிட்சை',
                'getLength'      => 15,
                'getPunycode'    => 'xn--zkc6cc5bi7f6e.xn--hlcj6aya9esc7a' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'உதாரணம்.பரிட்சை',
                '__toString'  => 'உதாரணம்.பரிட்சை',
                'getLength'   => 15,
                'getPunycode' => 'xn--zkc6cc5bi7f6e.xn--hlcj6aya9esc7a' ) ),
    ),
// TEST: Hebrew Yiddish בײַשפּיל.טעסט
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'בײַשפּיל.טעסט',
                '__toString'     => 'בײַשפּיל.טעסט',
                'getLength'      => 13,
                'getPunycode'    => 'xn--fdbk5d8ap9b8a8d.xn--deba0ad' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'בײַשפּיל.טעסט',
                '__toString'  => 'בײַשפּיל.טעסט',
                'getLength'   => 13,
                'getPunycode' => 'xn--fdbk5d8ap9b8a8d.xn--deba0ad' ) ),
    ),
// TEST: Ge'ez Amharic አማርኛ.idn.icann.org
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'አማርኛ.idn.icann.org',
                '__toString'     => 'አማርኛ.idn.icann.org',
                'getLength'      => 18,
                'getPunycode'    => 'xn--1xd0bwwra.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'አማርኛ.idn.icann.org',
                '__toString'        => 'አማርኛ.idn.icann.org',
                'getLength'         => 18,
                'getPunycode'       => 'xn--1xd0bwwra.idn.icann.org' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'አማርኛ.idn.icann.org',
                '__toString'     => 'አማርኛ.idn.icann.org',
                'getLength'      => 18,
                'getPunycode'    => 'xn--1xd0bwwra.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'አማርኛ.idn.icann.org',
                '__toString'  => 'አማርኛ.idn.icann.org',
                'getLength'   => 18,
                'getPunycode' => 'xn--1xd0bwwra.idn.icann.org' ) ),
    ),
// TEST: Bengali বাংলা.idn.icann.org
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'বাংলা.idn.icann.org',
                '__toString'     => 'বাংলা.idn.icann.org',
                'getLength'      => 19,
                'getPunycode'    => 'xn--54b7fta0cc.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'বাংলা.idn.icann.org',
                '__toString'  => 'বাংলা.idn.icann.org',
                'getLength'   => 19,
                'getPunycode' => 'xn--54b7fta0cc.idn.icann.org' ) ),
    ),
// TEST: Hebrew עברית.idn.icann.org
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'עברית.idn.icann.org',
                '__toString'     => 'עברית.idn.icann.org',
                'getLength'      => 19,
                'getPunycode'    => 'xn--5dbqzzl.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'עברית.idn.icann.org',
                '__toString'        => 'עברית.idn.icann.org',
                'getLength'         => 19,
                'getPunycode'       => 'xn--5dbqzzl.idn.icann.org' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'עברית.idn.icann.org',
                '__toString'     => 'עברית.idn.icann.org',
                'getLength'      => 19,
                'getPunycode'    => 'xn--5dbqzzl.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'עברית.idn.icann.org',
                '__toString'  => 'עברית.idn.icann.org',
                'getLength'   => 19,
                'getPunycode' => 'xn--5dbqzzl.idn.icann.org' ) ),
    ),
// TEST: Khmer ភាសាខ្មែរ.idn.icann.org
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => FALSE,
                'getValue'       => NULL,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => NULL ),
            'tldnomandatory' => array(
                'isvalid'           => FALSE,
                'getValue'          => NULL,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => NULL ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'ភាសាខ្មែរ.idn.icann.org',
                '__toString'     => 'ភាសាខ្មែរ.idn.icann.org',
                'getLength'      => 23,
                'getPunycode'    => 'xn--j2e7beiw1lb2hqg.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'ភាសាខ្មែរ.idn.icann.org',
                '__toString'  => 'ភាសាខ្មែរ.idn.icann.org',
                'getLength'   => 23,
                'getPunycode' => 'xn--j2e7beiw1lb2hqg.idn.icann.org' ) ),
    ),
// TEST: Thai ไทย.idn.icann.org
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'ไทย.idn.icann.org',
                '__toString'     => 'ไทย.idn.icann.org',
                'getLength'      => 17,
                'getPunycode'    => 'xn--o3cw4h.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'ไทย.idn.icann.org',
                '__toString'        => 'ไทย.idn.icann.org',
                'getLength'         => 17,
                'getPunycode'       => 'xn--o3cw4h.idn.icann.org' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'ไทย.idn.icann.org',
                '__toString'     => 'ไทย.idn.icann.org',
                'getLength'      => 17,
                'getPunycode'    => 'xn--o3cw4h.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'ไทย.idn.icann.org',
                '__toString'  => 'ไทย.idn.icann.org',
                'getLength'   => 17,
                'getPunycode' => 'xn--o3cw4h.idn.icann.org' ) ),
    ),
// TEST: Persian Urdu اردو.idn.icann.org
    array( 'expected-idn' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'اردو.idn.icann.org',
                '__toString'     => 'اردو.idn.icann.org',
                'getLength'      => 18,
                'getPunycode'    => 'xn--mgbqf7g.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'           => TRUE,
                'getValue'          => 'اردو.idn.icann.org',
                '__toString'        => 'اردو.idn.icann.org',
                'getLength'         => 18,
                'getPunycode'       => 'xn--mgbqf7g.idn.icann.org' ) ),
        'expected-punycode' => array(
            'tldmandatory' => array(
                'isvalid'        => TRUE,
                'getValue'       => 'اردو.idn.icann.org',
                '__toString'     => 'اردو.idn.icann.org',
                'getLength'      => 18,
                'getPunycode'    => 'xn--mgbqf7g.idn.icann.org' ),
            'tldnomandatory' => array(
                'isvalid'     => TRUE,
                'getValue'    => 'اردو.idn.icann.org',
                '__toString'  => 'اردو.idn.icann.org',
                'getLength'   => 18,
                'getPunycode' => 'xn--mgbqf7g.idn.icann.org' ) ),
    ),
);