<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = [
// DNS VALID
// TEST: example.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'example.com',
                '__toString'     => 'example.com',
                'getLength'      => 11,
                'getPunycode'    => 'example.com' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'example.com',
                '__toString'        => 'example.com',
                'getLength'         => 11,
                'getPunycode'       => 'example.com' ] ],
        'expected-punycode' => [
            'tldmandatory' => [ 'isvalid'        => true,
                'getValue'       => 'example.com',
                '__toString'     => 'example.com',
                'getLength'      => 11,
                'getPunycode'    => 'example.com' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'example.com',
                '__toString'  => 'example.com',
                'getLength'   => 11,
                'getPunycode' => 'example.com' ] ],
    ],
// TEST: example.museum
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'example.museum',
                '__toString'     => 'example.museum',
                'getLength'      => 14,
                'getPunycode'    => 'example.museum' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'example.museum',
                '__toString'        => 'example.museum',
                'getLength'         => 14,
                'getPunycode'       => 'example.museum' ] ],
        'expected-punycode' => [
            'tldmandatory' => [ 'isvalid'        => true,
                'getValue'       => 'example.museum',
                '__toString'     => 'example.museum',
                'getLength'      => 14,
                'getPunycode'    => 'example.museum' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'example.museum',
                '__toString'  => 'example.museum',
                'getLength'   => 14,
                'getPunycode' => 'example.museum' ] ],
    ],
// TEST: d.hatena.ne.jp
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'd.hatena.ne.jp',
                '__toString'     => 'd.hatena.ne.jp',
                'getLength'      => 14,
                'getPunycode'    => 'd.hatena.ne.jp' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'd.hatena.ne.jp',
                '__toString'        => 'd.hatena.ne.jp',
                'getLength'         => 14,
                'getPunycode'       => 'd.hatena.ne.jp' ] ],
        'expected-punycode' => [
            'tldmandatory' => [ 'isvalid'        => true,
                'getValue'       => 'd.hatena.ne.jp',
                '__toString'     => 'd.hatena.ne.jp',
                'getLength'      => 14,
                'getPunycode'    => 'd.hatena.ne.jp' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'd.hatena.ne.jp',
                '__toString'  => 'd.hatena.ne.jp',
                'getLength'   => 14,
                'getPunycode' => 'd.hatena.ne.jp' ] ],
    ],
// TEST: 123example.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '123example.com',
                '__toString'     => '123example.com',
                'getLength'      => 14,
                'getPunycode'    => '123example.com' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => '123example.com',
                '__toString'        => '123example.com',
                'getLength'         => 14,
                'getPunycode'       => '123example.com' ] ],
        'expected-punycode' => [
            'tldmandatory' => [ 'isvalid'        => true,
                'getValue'       => '123example.com',
                '__toString'     => '123example.com',
                'getLength'      => 14,
                'getPunycode'    => '123example.com' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => '123example.com',
                '__toString'  => '123example.com',
                'getLength'   => 14,
                'getPunycode' => '123example.com' ] ],
    ],
// TEST: 1and1.fr
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '1and1.fr',
                '__toString'     => '1and1.fr',
                'getLength'      => 8,
                'getPunycode'    => '1and1.fr' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => '1and1.fr',
                '__toString'        => '1and1.fr',
                'getLength'         => 8,
                'getPunycode'       => '1and1.fr' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '1and1.fr',
                '__toString'     => '1and1.fr',
                'getLength'      => 8,
                'getPunycode'    => '1and1.fr' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => '1and1.fr',
                '__toString'  => '1and1.fr',
                'getLength'   => 8,
                'getPunycode' => '1and1.fr' ] ],
    ],
// TEST: doma-in.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'doma-in.com',
                '__toString'     => 'doma-in.com',
                'getLength'      => 11,
                'getPunycode'    => 'doma-in.com' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'doma-in.com',
                '__toString'        => 'doma-in.com',
                'getLength'         => 11,
                'getPunycode'       => 'doma-in.com' ] ],
        'expected-punycode' => [
            'tldmandatory' => [ 'isvalid'        => true,
                'getValue'       => 'doma-in.com',
                '__toString'     => 'doma-in.com',
                'getLength'      => 11,
                'getPunycode'    => 'doma-in.com' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'doma-in.com',
                '__toString'  => 'doma-in.com',
                'getLength'   => 11,
                'getPunycode' => 'doma-in.com' ] ],
    ],
// TEST: domain.co.uk
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'domain.co.uk',
                '__toString'     => 'domain.co.uk',
                'getLength'      => 12,
                'getPunycode'    => 'domain.co.uk' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'domain.co.uk',
                '__toString'        => 'domain.co.uk',
                'getLength'         => 12,
                'getPunycode'       => 'domain.co.uk' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'domain.co.uk',
                '__toString'     => 'domain.co.uk',
                'getLength'      => 12,
                'getPunycode'    => 'domain.co.uk' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'domain.co.uk',
                '__toString'  => 'domain.co.uk',
                'getLength'   => 12,
                'getPunycode' => 'domain.co.uk' ] ],
    ],
// DNS NOT VALID
// TEST: example..
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: example..com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: example,com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: exam_ple.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: .example.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: -domain.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: domain-.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: do--main.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: yah&oo.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: y*ahoo.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: ya#hoo
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: test.com / http://www.test.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: ~ex%20ample
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: §bad
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: don?t.know
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TLD
// TEST: www.danger1com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'www.danger1com',
                '__toString'     => 'www.danger1com',
                'getLength'      => 14,
                'getPunycode'    => 'www.danger1com' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'www.danger1com',
                '__toString'        => 'www.danger1com',
                'getLength'         => 14,
                'getPunycode'       => 'www.danger1com' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'www.danger1com',
                '__toString'     => 'www.danger1com',
                'getLength'      => 14,
                'getPunycode'    => 'www.danger1com' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'www.danger1com',
                '__toString'  => 'www.danger1com',
                'getLength'   => 14,
                'getPunycode' => 'www.danger1com' ] ],
    ],
// TEST: dangercom
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'dangercom',
                '__toString'        => 'dangercom',
                'getLength'         => 9,
                'getPunycode'       => 'dangercom' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'dangercom',
                '__toString'  => 'dangercom',
                'getLength'   => 9,
                'getPunycode' => 'dangercom' ] ],
    ],
// TEST: www.dangercom
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'www.dangercom',
                '__toString'     => 'www.dangercom',
                'getLength'      => 13,
                'getPunycode'    => 'www.dangercom' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'www.dangercom',
                '__toString'        => 'www.dangercom',
                'getLength'         => 13,
                'getPunycode'       => 'www.dangercom' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'www.dangercom',
                '__toString'     => 'www.dangercom',
                'getLength'      => 13,
                'getPunycode'    => 'www.dangercom' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'www.dangercom',
                '__toString'  => 'www.dangercom',
                'getLength'   => 13,
                'getPunycode' => 'www.dangercom' ] ],
    ],
// TEST: example.f1
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'example.f1',
                '__toString'     => 'example.f1',
                'getLength'      => 10,
                'getPunycode'    => 'example.f1' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'example.f1',
                '__toString'        => 'example.f1',
                'getLength'         => 10,
                'getPunycode'       => 'example.f1' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'example.f1',
                '__toString'     => 'example.f1',
                'getLength'      => 10,
                'getPunycode'    => 'example.f1' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'example.f1',
                '__toString'  => 'example.f1',
                'getLength'   => 10,
                'getPunycode' => 'example.f1' ] ],
    ],
// TEST: example.f-r
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'example.f-r',
                '__toString'     => 'example.f-r',
                'getLength'      => 11,
                'getPunycode'    => 'example.f-r' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'example.f-r',
                '__toString'        => 'example.f-r',
                'getLength'         => 11,
                'getPunycode'       => 'example.f-r' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'example.f-r',
                '__toString'     => 'example.f-r',
                'getLength'      => 11,
                'getPunycode'    => 'example.f-r' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'example.f-r',
                '__toString'  => 'example.f-r',
                'getLength'   => 11,
                'getPunycode' => 'example.f-r' ] ],
    ],
// TLD NOT VALID
// TEST: example.c
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ] ],
    ],
// TEST: example.123
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ] ],
    ],
// TEST: example.-fr
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: example.fr-
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// LOCAL VALID
// TEST: localhost
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'localhost',
                '__toString'        => 'localhost',
                'getLength'         => 9,
                'getPunycode'       => 'localhost' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'localhost',
                '__toString'  => 'localhost',
                'getLength'   => 9,
                'getPunycode' => 'localhost' ] ],
    ],
// TEST: localhost.localdomain
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'localhost.localdomain',
                '__toString'     => 'localhost.localdomain',
                'getLength'      => 21,
                'getPunycode'    => 'localhost.localdomain' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'localhost.localdomain',
                '__toString'        => 'localhost.localdomain',
                'getLength'         => 21,
                'getPunycode'       => 'localhost.localdomain' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'localhost.localdomain',
                '__toString'     => 'localhost.localdomain',
                'getLength'      => 21,
                'getPunycode'    => 'localhost.localdomain' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'localhost.localdomain',
                '__toString'  => 'localhost.localdomain',
                'getLength'   => 21,
                'getPunycode' => 'localhost.localdomain' ] ],
    ],
// LOCAL NOT VALID
// TEST: local host
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: .localhost
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// PUNYCODE NOT VALID
// TEST: xn--brger-x45d2va.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: xn--bürger.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: xn--
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// PARTIAL
// TEST: example.
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: example.com.
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// TEST: ~ex%20ample.
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'     => false,
                'getValue'    => null,
                '__toString'  => '',
                'getLength'   => 0,
                'getPunycode' => null ] ],
    ],
// IDN VALID
// TEST: café-glacé.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'café-glacé.com',
                '__toString'     => 'café-glacé.com',
                'getLength'      => 14,
                'getPunycode'    => 'xn--caf-glac-d1af.com' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'café-glacé.com',
                '__toString'        => 'café-glacé.com',
                'getLength'         => 14,
                'getPunycode'       => 'xn--caf-glac-d1af.com' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'café-glacé.com',
                '__toString'     => 'café-glacé.com',
                'getLength'      => 14,
                'getPunycode'    => 'xn--caf-glac-d1af.com' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'café-glacé.com',
                '__toString'  => 'café-glacé.com',
                'getLength'   => 14,
                'getPunycode' => 'xn--caf-glac-d1af.com' ] ],
    ],
// TEST: café.glacé.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'café.glacé.com',
                '__toString'     => 'café.glacé.com',
                'getLength'      => 14,
                'getPunycode'    => 'xn--caf-dma.xn--glac-epa.com' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'café.glacé.com',
                '__toString'        => 'café.glacé.com',
                'getLength'         => 14,
                'getPunycode'       => 'xn--caf-dma.xn--glac-epa.com' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'café.glacé.com',
                '__toString'     => 'café.glacé.com',
                'getLength'      => 14,
                'getPunycode'    => 'xn--caf-dma.xn--glac-epa.com' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'café.glacé.com',
                '__toString'  => 'café.glacé.com',
                'getLength'   => 14,
                'getPunycode' => 'xn--caf-dma.xn--glac-epa.com' ] ],
    ],
// TEST: 1café.glacé2.com
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '1café.glacé2.com',
                '__toString'     => '1café.glacé2.com',
                'getLength'      => 16,
                'getPunycode'    => 'xn--1caf-epa.xn--glac2-esa.com' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => '1café.glacé2.com',
                '__toString'        => '1café.glacé2.com',
                'getLength'         => 16,
                'getPunycode'       => 'xn--1caf-epa.xn--glac2-esa.com' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '1café.glacé2.com',
                '__toString'     => '1café.glacé2.com',
                'getLength'      => 16,
                'getPunycode'    => 'xn--1caf-epa.xn--glac2-esa.com' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => '1café.glacé2.com',
                '__toString'  => '1café.glacé2.com',
                'getLength'   => 16,
                'getPunycode' => 'xn--1caf-epa.xn--glac2-esa.com' ] ],
    ],
// TEST: 上海世博会.中国
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '上海世博会.中国',
                '__toString'     => '上海世博会.中国',
                'getLength'      => 8,
                'getPunycode'    => 'xn--fhqya62el8j7s3b.xn--fiqs8s' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => '上海世博会.中国',
                '__toString'        => '上海世博会.中国',
                'getLength'         => 8,
                'getPunycode'       => 'xn--fhqya62el8j7s3b.xn--fiqs8s' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '上海世博会.中国',
                '__toString'     => '上海世博会.中国',
                'getLength'      => 8,
                'getPunycode'    => 'xn--fhqya62el8j7s3b.xn--fiqs8s' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => '上海世博会.中国',
                '__toString'  => '上海世博会.中国',
                'getLength'   => 8,
                'getPunycode' => 'xn--fhqya62el8j7s3b.xn--fiqs8s' ] ],
    ],
// TEST: Latin supernovæ.fr
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'supernovæ.fr',
                '__toString'     => 'supernovæ.fr',
                'getLength'      => 12,
                'getPunycode'    => 'xn--supernov-q0a.fr' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'supernovæ.fr',
                '__toString'        => 'supernovæ.fr',
                'getLength'         => 12,
                'getPunycode'       => 'xn--supernov-q0a.fr' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'supernovæ.fr',
                '__toString'     => 'supernovæ.fr',
                'getLength'      => 12,
                'getPunycode'    => 'xn--supernov-q0a.fr' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'supernovæ.fr',
                '__toString'  => 'supernovæ.fr',
                'getLength'   => 12,
                'getPunycode' => 'xn--supernov-q0a.fr' ] ],
    ],
// TEST: Arabic مثال.إختبار
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'مثال.إختبار',
                '__toString'     => 'مثال.إختبار',
                'getLength'      => 11,
                'getPunycode'    => 'xn--mgbh0fb.xn--kgbechtv' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'مثال.إختبار',
                '__toString'        => 'مثال.إختبار',
                'getLength'         => 11,
                'getPunycode'       => 'xn--mgbh0fb.xn--kgbechtv' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'مثال.إختبار',
                '__toString'     => 'مثال.إختبار',
                'getLength'      => 11,
                'getPunycode'    => 'xn--mgbh0fb.xn--kgbechtv' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'مثال.إختبار',
                '__toString'  => 'مثال.إختبار',
                'getLength'   => 11,
                'getPunycode' => 'xn--mgbh0fb.xn--kgbechtv' ] ],
    ],
// TEST: Simplified Chinese 例子.测试
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '例子.测试',
                '__toString'     => '例子.测试',
                'getLength'      => 5,
                'getPunycode'    => 'xn--fsqu00a.xn--0zwm56d' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => '例子.测试',
                '__toString'        => '例子.测试',
                'getLength'         => 5,
                'getPunycode'       => 'xn--fsqu00a.xn--0zwm56d' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '例子.测试',
                '__toString'     => '例子.测试',
                'getLength'      => 5,
                'getPunycode'    => 'xn--fsqu00a.xn--0zwm56d' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => '例子.测试',
                '__toString'  => '例子.测试',
                'getLength'   => 5,
                'getPunycode' => 'xn--fsqu00a.xn--0zwm56d' ] ],
    ],
// TEST: Traditional Chinese 例子.測試
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '例子.測試',
                '__toString'     => '例子.測試',
                'getLength'      => 5,
                'getPunycode'    => 'xn--fsqu00a.xn--g6w251d' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => '例子.測試',
                '__toString'        => '例子.測試',
                'getLength'         => 5,
                'getPunycode'       => 'xn--fsqu00a.xn--g6w251d' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '例子.測試',
                '__toString'     => '例子.測試',
                'getLength'      => 5,
                'getPunycode'    => 'xn--fsqu00a.xn--g6w251d' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => '例子.測試',
                '__toString'  => '例子.測試',
                'getLength'   => 5,
                'getPunycode' => 'xn--fsqu00a.xn--g6w251d' ] ],
    ],
// TEST: Greek παράδειγμα.δοκιμή
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'παράδειγμα.δοκιμή',
                '__toString'     => 'παράδειγμα.δοκιμή',
                'getLength'      => 17,
                'getPunycode'    => 'xn--hxajbheg2az3al.xn--jxalpdlp' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'παράδειγμα.δοκιμή',
                '__toString'        => 'παράδειγμα.δοκιμή',
                'getLength'         => 17,
                'getPunycode'       => 'xn--hxajbheg2az3al.xn--jxalpdlp' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'παράδειγμα.δοκιμή',
                '__toString'     => 'παράδειγμα.δοκιμή',
                'getLength'      => 17,
                'getPunycode'    => 'xn--hxajbheg2az3al.xn--jxalpdlp' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'παράδειγμα.δοκιμή',
                '__toString'  => 'παράδειγμα.δοκιμή',
                'getLength'   => 17,
                'getPunycode' => 'xn--hxajbheg2az3al.xn--jxalpdlp' ] ],
    ],
// TEST: Devanagari Hindi उदाहरण.परीक्षा
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'उदाहरण.परीक्षा',
                '__toString'     => 'उदाहरण.परीक्षा',
                'getLength'      => 14,
                'getPunycode'    => 'xn--p1b6ci4b4b3a.xn--11b5bs3a9aj6g' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'उदाहरण.परीक्षा',
                '__toString'  => 'उदाहरण.परीक्षा',
                'getLength'   => 14,
                'getPunycode' => 'xn--p1b6ci4b4b3a.xn--11b5bs3a9aj6g' ] ],
    ],
// TEST: Kanji, Hiragana, Katakana Japanese 例え.テスト
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '例え.テスト',
                '__toString'     => '例え.テスト',
                'getLength'      => 6,
                'getPunycode'    => 'xn--r8jz45g.xn--zckzah' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => '例え.テスト',
                '__toString'        => '例え.テスト',
                'getLength'         => 6,
                'getPunycode'       => 'xn--r8jz45g.xn--zckzah' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '例え.テスト',
                '__toString'     => '例え.テスト',
                'getLength'      => 6,
                'getPunycode'    => 'xn--r8jz45g.xn--zckzah' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => '例え.テスト',
                '__toString'  => '例え.テスト',
                'getLength'   => 6,
                'getPunycode' => 'xn--r8jz45g.xn--zckzah' ] ],
    ],
// TEST: Hangul Korean 실례.테스트
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '실례.테스트',
                '__toString'     => '실례.테스트',
                'getLength'      => 6,
                'getPunycode'    => 'xn--9n2bp8q.xn--9t4b11yi5a' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => '실례.테스트',
                '__toString'        => '실례.테스트',
                'getLength'         => 6,
                'getPunycode'       => 'xn--9n2bp8q.xn--9t4b11yi5a' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => '실례.테스트',
                '__toString'     => '실례.테스트',
                'getLength'      => 6,
                'getPunycode'    => 'xn--9n2bp8q.xn--9t4b11yi5a' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => '실례.테스트',
                '__toString'  => '실례.테스트',
                'getLength'   => 6,
                'getPunycode' => 'xn--9n2bp8q.xn--9t4b11yi5a' ] ],
    ],
// TEST: Perso-Arabic مثال.آزمایشی
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'مثال.آزمایشی',
                '__toString'     => 'مثال.آزمایشی',
                'getLength'      => 12,
                'getPunycode'    => 'xn--mgbh0fb.xn--hgbk6aj7f53bba' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'مثال.آزمایشی',
                '__toString'        => 'مثال.آزمایشی',
                'getLength'         => 12,
                'getPunycode'       => 'xn--mgbh0fb.xn--hgbk6aj7f53bba' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'مثال.آزمایشی',
                '__toString'     => 'مثال.آزمایشی',
                'getLength'      => 12,
                'getPunycode'    => 'xn--mgbh0fb.xn--hgbk6aj7f53bba' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'مثال.آزمایشی',
                '__toString'  => 'مثال.آزمایشی',
                'getLength'   => 12,
                'getPunycode' => 'xn--mgbh0fb.xn--hgbk6aj7f53bba' ] ],
    ],
// TEST: Cyrillic Russian пример.испытание
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'пример.испытание',
                '__toString'     => 'пример.испытание',
                'getLength'      => 16,
                'getPunycode'    => 'xn--e1afmkfd.xn--80akhbyknj4f' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'пример.испытание',
                '__toString'        => 'пример.испытание',
                'getLength'         => 16,
                'getPunycode'       => 'xn--e1afmkfd.xn--80akhbyknj4f' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'пример.испытание',
                '__toString'     => 'пример.испытание',
                'getLength'      => 16,
                'getPunycode'    => 'xn--e1afmkfd.xn--80akhbyknj4f' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'пример.испытание',
                '__toString'  => 'пример.испытание',
                'getLength'   => 16,
                'getPunycode' => 'xn--e1afmkfd.xn--80akhbyknj4f' ] ],
    ],
// TEST: Tamil உதாரணம்.பரிட்சை
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'உதாரணம்.பரிட்சை',
                '__toString'     => 'உதாரணம்.பரிட்சை',
                'getLength'      => 15,
                'getPunycode'    => 'xn--zkc6cc5bi7f6e.xn--hlcj6aya9esc7a' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'உதாரணம்.பரிட்சை',
                '__toString'  => 'உதாரணம்.பரிட்சை',
                'getLength'   => 15,
                'getPunycode' => 'xn--zkc6cc5bi7f6e.xn--hlcj6aya9esc7a' ] ],
    ],
// TEST: Hebrew Yiddish בײַשפּיל.טעסט
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'בײַשפּיל.טעסט',
                '__toString'     => 'בײַשפּיל.טעסט',
                'getLength'      => 13,
                'getPunycode'    => 'xn--fdbk5d8ap9b8a8d.xn--deba0ad' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'בײַשפּיל.טעסט',
                '__toString'  => 'בײַשפּיל.טעסט',
                'getLength'   => 13,
                'getPunycode' => 'xn--fdbk5d8ap9b8a8d.xn--deba0ad' ] ],
    ],
// TEST: Ge'ez Amharic አማርኛ.idn.icann.org
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'አማርኛ.idn.icann.org',
                '__toString'     => 'አማርኛ.idn.icann.org',
                'getLength'      => 18,
                'getPunycode'    => 'xn--1xd0bwwra.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'አማርኛ.idn.icann.org',
                '__toString'        => 'አማርኛ.idn.icann.org',
                'getLength'         => 18,
                'getPunycode'       => 'xn--1xd0bwwra.idn.icann.org' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'አማርኛ.idn.icann.org',
                '__toString'     => 'አማርኛ.idn.icann.org',
                'getLength'      => 18,
                'getPunycode'    => 'xn--1xd0bwwra.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'አማርኛ.idn.icann.org',
                '__toString'  => 'አማርኛ.idn.icann.org',
                'getLength'   => 18,
                'getPunycode' => 'xn--1xd0bwwra.idn.icann.org' ] ],
    ],
// TEST: Bengali বাংলা.idn.icann.org
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'বাংলা.idn.icann.org',
                '__toString'     => 'বাংলা.idn.icann.org',
                'getLength'      => 19,
                'getPunycode'    => 'xn--54b7fta0cc.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'বাংলা.idn.icann.org',
                '__toString'  => 'বাংলা.idn.icann.org',
                'getLength'   => 19,
                'getPunycode' => 'xn--54b7fta0cc.idn.icann.org' ] ],
    ],
// TEST: Hebrew עברית.idn.icann.org
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'עברית.idn.icann.org',
                '__toString'     => 'עברית.idn.icann.org',
                'getLength'      => 19,
                'getPunycode'    => 'xn--5dbqzzl.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'עברית.idn.icann.org',
                '__toString'        => 'עברית.idn.icann.org',
                'getLength'         => 19,
                'getPunycode'       => 'xn--5dbqzzl.idn.icann.org' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'עברית.idn.icann.org',
                '__toString'     => 'עברית.idn.icann.org',
                'getLength'      => 19,
                'getPunycode'    => 'xn--5dbqzzl.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'עברית.idn.icann.org',
                '__toString'  => 'עברית.idn.icann.org',
                'getLength'   => 19,
                'getPunycode' => 'xn--5dbqzzl.idn.icann.org' ] ],
    ],
// TEST: Khmer ភាសាខ្មែរ.idn.icann.org
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => false,
                'getValue'       => null,
                '__toString'     => '',
                'getLength'      => 0,
                'getPunycode'    => null ],
            'tldnomandatory' => [
                'isvalid'           => false,
                'getValue'          => null,
                '__toString'        => '',
                'getLength'         => 0,
                'getPunycode'       => null ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'ភាសាខ្មែរ.idn.icann.org',
                '__toString'     => 'ភាសាខ្មែរ.idn.icann.org',
                'getLength'      => 23,
                'getPunycode'    => 'xn--j2e7beiw1lb2hqg.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'ភាសាខ្មែរ.idn.icann.org',
                '__toString'  => 'ភាសាខ្មែរ.idn.icann.org',
                'getLength'   => 23,
                'getPunycode' => 'xn--j2e7beiw1lb2hqg.idn.icann.org' ] ],
    ],
// TEST: Thai ไทย.idn.icann.org
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'ไทย.idn.icann.org',
                '__toString'     => 'ไทย.idn.icann.org',
                'getLength'      => 17,
                'getPunycode'    => 'xn--o3cw4h.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'ไทย.idn.icann.org',
                '__toString'        => 'ไทย.idn.icann.org',
                'getLength'         => 17,
                'getPunycode'       => 'xn--o3cw4h.idn.icann.org' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'ไทย.idn.icann.org',
                '__toString'     => 'ไทย.idn.icann.org',
                'getLength'      => 17,
                'getPunycode'    => 'xn--o3cw4h.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'ไทย.idn.icann.org',
                '__toString'  => 'ไทย.idn.icann.org',
                'getLength'   => 17,
                'getPunycode' => 'xn--o3cw4h.idn.icann.org' ] ],
    ],
// TEST: Persian Urdu اردو.idn.icann.org
    [ 'expected-idn' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'اردو.idn.icann.org',
                '__toString'     => 'اردو.idn.icann.org',
                'getLength'      => 18,
                'getPunycode'    => 'xn--mgbqf7g.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'           => true,
                'getValue'          => 'اردو.idn.icann.org',
                '__toString'        => 'اردو.idn.icann.org',
                'getLength'         => 18,
                'getPunycode'       => 'xn--mgbqf7g.idn.icann.org' ] ],
        'expected-punycode' => [
            'tldmandatory' => [
                'isvalid'        => true,
                'getValue'       => 'اردو.idn.icann.org',
                '__toString'     => 'اردو.idn.icann.org',
                'getLength'      => 18,
                'getPunycode'    => 'xn--mgbqf7g.idn.icann.org' ],
            'tldnomandatory' => [
                'isvalid'     => true,
                'getValue'    => 'اردو.idn.icann.org',
                '__toString'  => 'اردو.idn.icann.org',
                'getLength'   => 18,
                'getPunycode' => 'xn--mgbqf7g.idn.icann.org' ] ],
    ],
];
