<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = [
//array( 'label'=>'TEST: NULL',       'test'=>NULL ),
[ 'expected' => [ 'exception' => 3, 'send' => false ] ],
//array( 'label'=>'TEST: EMPTY',      'test'=>'' ),
[ 'expected' => [ 'exception' => 3, 'send' => false ] ],
//array( 'label'=>'TEST: DIRECTORY',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR),
[ 'expected' => [ 'exception' => 3, 'send' => false ] ],
//array( 'label'=>'TEST: notadir',    'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'notadir' ),
[ 'expected' => [ 'exception' => 0, 'send' => true ] ],
//array( 'label'=>'TEST: source.php', 'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'source.php' ),
[ 'expected' => [ 'exception' => 0, 'send' => true ] ],
//array( 'label'=>'TEST: image.bmp',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.bmp' ),
[ 'expected' => [ 'exception' => 0, 'send' => true ] ],
//array( 'label'=>'TEST: image.gif',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.gif' ),
[ 'expected' => [ 'exception' => 0, 'send' => true ] ],
//array( 'label'=>'TEST: image.jpg',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.jpg' ),
[ 'expected' => [ 'exception' => 0, 'send' => true ] ],
//array( 'label'=>'TEST: image.png',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.png' ),
[ 'expected' => [ 'exception' => 0, 'send' => true ] ],
//array( 'label'=>'TEST: image',      'test'=>$sBuffer20121015 . DIRECTORY_SEPARATOR . 'image' ),
[ 'expected' => [ 'exception' => 0, 'send' => true ] ],
//array( 'label'=>'TEST: audio.mp3',  'test'=>$sBuffer20121015 . DIRECTORY_SEPARATOR . 'audio.mp3' ),
[ 'expected' => [ 'exception' => 0, 'send' => true ] ],
//array( 'label'=>'TEST: audio',      'test'=>$sBuffer20121015 . DIRECTORY_SEPARATOR . 'audio' ),
[ 'expected' => [ 'exception' => 0, 'send' => true ] ],
];
