<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = array(
//array( 'label'=>'TEST: NULL',       'test'=>NULL ),
array( 'expected'=>array( 'exception'=>3, 'send'=>FALSE ) ),
//array( 'label'=>'TEST: EMPTY',      'test'=>'' ),
array( 'expected'=>array( 'exception'=>3, 'send'=>FALSE ) ),
//array( 'label'=>'TEST: DIRECTORY',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR),
array( 'expected'=>array( 'exception'=>3, 'send'=>FALSE ) ),
//array( 'label'=>'TEST: notadir',    'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'notadir' ),
array( 'expected'=>array( 'exception'=>0, 'send'=>TRUE ) ),
//array( 'label'=>'TEST: source.php', 'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'source.php' ),
array( 'expected'=>array( 'exception'=>0, 'send'=>TRUE ) ),
//array( 'label'=>'TEST: image.bmp',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.bmp' ),
array( 'expected'=>array( 'exception'=>0, 'send'=>TRUE ) ),
//array( 'label'=>'TEST: image.gif',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.gif' ),
array( 'expected'=>array( 'exception'=>0, 'send'=>TRUE ) ),
//array( 'label'=>'TEST: image.jpg',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.jpg' ),
array( 'expected'=>array( 'exception'=>0, 'send'=>TRUE ) ),
//array( 'label'=>'TEST: image.png',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.png' ),
array( 'expected'=>array( 'exception'=>0, 'send'=>TRUE ) ),
//array( 'label'=>'TEST: image',      'test'=>$sBuffer20121015 . DIRECTORY_SEPARATOR . 'image' ),
array( 'expected'=>array( 'exception'=>0, 'send'=>TRUE ) ),
//array( 'label'=>'TEST: audio.mp3',  'test'=>$sBuffer20121015 . DIRECTORY_SEPARATOR . 'audio.mp3' ),
array( 'expected'=>array( 'exception'=>0, 'send'=>TRUE ) ),
//array( 'label'=>'TEST: audio',      'test'=>$sBuffer20121015 . DIRECTORY_SEPARATOR . 'audio' ),
array( 'expected'=>array( 'exception'=>0, 'send'=>TRUE ) ),
);