<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
return [
//[ 'label'=>'TEST: NULL',       'test'=>NULL ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 3, 'send'      => false ], 'fromextension' => [ 'exception' => 3,
                'send'      => false ] ] ],
//[ 'label'=>'TEST: EMPTY',      'test'=>'' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 3, 'send'      => false ], 'fromextension' => [ 'exception' => 3,
                'send'      => false ] ] ],
//[ 'label'=>'TEST: DIRECTORY',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 3, 'send'      => false ], 'fromextension' => [ 'exception' => 3,
                'send'      => false ] ] ],
//[ 'label'=>'TEST: notadir',    'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'notadir' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 2, 'send'      => false ], 'fromextension' => [ 'exception' => 3,
                'send'      => false ] ] ],
//[ 'label'=>'TEST: source.php', 'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'source.php' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 3, 'send'      => false ], 'fromextension' => [ 'exception' => 3,
                'send'      => false ] ] ],
//[ 'label'=>'TEST: image.bmp',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.bmp' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 0, 'send'      => true ], 'fromextension' => [ 'exception' => 3,
                'send'      => true ] ] ],
//[ 'label'=>'TEST: image.gif',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.gif' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 0, 'send'      => true ], 'fromextension' => [ 'exception' => 0,
                'send'      => true ] ] ],
//[ 'label'=>'TEST: image.jpg',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.jpg' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 0, 'send'      => true ], 'fromextension' => [ 'exception' => 0,
                'send'      => true ] ] ],
//[ 'label'=>'TEST: image.png',  'test'=>APPLICATION_PATH . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR . 'image.png' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 0, 'send'      => true ], 'fromextension' => [ 'exception' => 0,
                'send'      => true ] ] ],
//[ 'label'=>'TEST: image',      'test'=>$sBuffer20121015 . DIRECTORY_SEPARATOR . 'image' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 0, 'send'      => true ], 'fromextension' => [ 'exception' => 3,
                'send'      => false ] ] ],
//[ 'label'=>'TEST: audio.mp3',  'test'=>$sBuffer20121015 . DIRECTORY_SEPARATOR . 'audio.mp3' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 3, 'send'      => false ], 'fromextension' => [ 'exception' => 3,
                'send'      => false ] ] ],
//[ 'label'=>'TEST: audio',      'test'=>$sBuffer20121015 . DIRECTORY_SEPARATOR . 'audio' ),
    [ 'expected' => [ 'fromfile'      => [ 'exception' => 3, 'send'      => false ], 'fromextension' => [ 'exception' => 3,
                'send'      => false ] ] ],
];
