<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = array(
//array( 'label'=>'TEST: "­"' , 'test'=>'­'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x09)"' , 'test'=>'chr(0x09)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x0B)"' , 'test'=>'chr(0x0B)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x0A)"' , 'test'=>'chr(0x0A)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x0D)"' , 'test'=>'chr(0x0D)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x08)"' , 'test'=>'chr(0x08)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x0C)"' , 'test'=>'chr(0x0C)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x07)"' , 'test'=>'chr(0x07)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x1B)"' , 'test'=>'chr(0x1B)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "!"' , 'test'=>'!'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: """' , 'test'=>'"'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "#"' , 'test'=>'#'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "%"' , 'test'=>'%'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "&"' , 'test'=>'&'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "*"' , 'test'=>'*'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ","' , 'test'=>','),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "/"' , 'test'=>'/'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ":"' , 'test'=>':'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ";"' , 'test'=>';'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "?"' , 'test'=>'?'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "\"' , 'test'=>'\'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¡"' , 'test'=>'¡'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "·"' , 'test'=>'·'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¿"' , 'test'=>'¿'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "'"' , 'test'=>'''),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "."' , 'test'=>'.'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "-"' , 'test'=>'-'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "("' , 'test'=>'('),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ")"' , 'test'=>')'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "["' , 'test'=>'['),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "]"' , 'test'=>']'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "{"' , 'test'=>'{'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "}"' , 'test'=>'}'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "«"' , 'test'=>'«'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "»"' , 'test'=>'»'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "_"' , 'test'=>'_'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "²"' , 'test'=>'²'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "³"' , 'test'=>'³'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¹"' , 'test'=>'¹'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¼"' , 'test'=>'¼'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "½"' , 'test'=>'½'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¾"' , 'test'=>'¾'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¦"' , 'test'=>'¦'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "§"' , 'test'=>'§'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "©"' , 'test'=>'©'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "®"' , 'test'=>'®'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "°"' , 'test'=>'°'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¶"' , 'test'=>'¶'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "^"' , 'test'=>'^'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "`"' , 'test'=>'`'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¨"' , 'test'=>'¨'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¯"' , 'test'=>'¯'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "´"' , 'test'=>'´'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¸"' , 'test'=>'¸'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "$"' , 'test'=>'$'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¢"' , 'test'=>'¢'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "£"' , 'test'=>'£'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¤"' , 'test'=>'¤'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¥"' , 'test'=>'¥'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "+"' , 'test'=>'+'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "<"' , 'test'=>'<'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "="' , 'test'=>'='),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ">"' , 'test'=>'>'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "|"' , 'test'=>'|'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "~"' , 'test'=>'~'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¬"' , 'test'=>'¬'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "±"' , 'test'=>'±'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "×"' , 'test'=>'×'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "÷"' , 'test'=>'÷'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ª"' , 'test'=>'ª'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "µ"' , 'test'=>'µ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "º"' , 'test'=>'º'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "а"' , 'test'=>'а'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "б"' , 'test'=>'б'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "в"' , 'test'=>'в'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "г"' , 'test'=>'г'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "д"' , 'test'=>'д'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "е"' , 'test'=>'е'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ё"' , 'test'=>'ё'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ж"' , 'test'=>'ж'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "з"' , 'test'=>'з'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "и"' , 'test'=>'и'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "й"' , 'test'=>'й'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "к"' , 'test'=>'к'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "л"' , 'test'=>'л'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "м"' , 'test'=>'м'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "н"' , 'test'=>'н'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "о"' , 'test'=>'о'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "п"' , 'test'=>'п'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "р"' , 'test'=>'р'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "с"' , 'test'=>'с'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "т"' , 'test'=>'т'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "у"' , 'test'=>'у'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ф"' , 'test'=>'ф'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "х"' , 'test'=>'х'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ц"' , 'test'=>'ц'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ч"' , 'test'=>'ч'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ш"' , 'test'=>'ш'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "щ"' , 'test'=>'щ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "э"' , 'test'=>'э'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ю"' , 'test'=>'ю'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "я"' , 'test'=>'я'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ъ"' , 'test'=>'ъ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ы"' , 'test'=>'ы'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ь"' , 'test'=>'ь'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ø"' , 'test'=>'ø'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ù"' , 'test'=>'ù'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ú"' , 'test'=>'ú'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "û"' , 'test'=>'û'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ü"' , 'test'=>'ü'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ý"' , 'test'=>'ý'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "þ"' , 'test'=>'þ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ÿ"' , 'test'=>'ÿ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ß"' , 'test'=>'ß'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "à"' , 'test'=>'à'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "á"' , 'test'=>'á'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "â"' , 'test'=>'â'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ã"' , 'test'=>'ã'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ä"' , 'test'=>'ä'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "å"' , 'test'=>'å'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "æ"' , 'test'=>'æ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ç"' , 'test'=>'ç'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "è"' , 'test'=>'è'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "é"' , 'test'=>'é'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ê"' , 'test'=>'ê'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ë"' , 'test'=>'ë'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ì"' , 'test'=>'ì'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "í"' , 'test'=>'í'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "î"' , 'test'=>'î'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ï"' , 'test'=>'ï'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ð"' , 'test'=>'ð'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ñ"' , 'test'=>'ñ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ò"' , 'test'=>'ò'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ó"' , 'test'=>'ó'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ô"' , 'test'=>'ô'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "õ"' , 'test'=>'õ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ö"' , 'test'=>'ö'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "А"' , 'test'=>'А'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Б"' , 'test'=>'Б'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "В"' , 'test'=>'В'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Г"' , 'test'=>'Г'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Д"' , 'test'=>'Д'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Е"' , 'test'=>'Е'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ё"' , 'test'=>'Ё'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ж"' , 'test'=>'Ж'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "З"' , 'test'=>'З'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "И"' , 'test'=>'И'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Й"' , 'test'=>'Й'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "К"' , 'test'=>'К'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Л"' , 'test'=>'Л'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "М"' , 'test'=>'М'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Н"' , 'test'=>'Н'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "О"' , 'test'=>'О'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "П"' , 'test'=>'П'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Р"' , 'test'=>'Р'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "С"' , 'test'=>'С'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Т"' , 'test'=>'Т'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "У"' , 'test'=>'У'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ф"' , 'test'=>'Ф'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Х"' , 'test'=>'Х'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ц"' , 'test'=>'Ц'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ч"' , 'test'=>'Ч'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ш"' , 'test'=>'Ш'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Щ"' , 'test'=>'Щ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Э"' , 'test'=>'Э'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ю"' , 'test'=>'Ю'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Я"' , 'test'=>'Я'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ъ"' , 'test'=>'Ъ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ы"' , 'test'=>'Ы'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ь"' , 'test'=>'Ь'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "À"' , 'test'=>'À'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Á"' , 'test'=>'Á'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Â"' , 'test'=>'Â'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ã"' , 'test'=>'Ã'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ä"' , 'test'=>'Ä'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Å"' , 'test'=>'Å'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Æ"' , 'test'=>'Æ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ç"' , 'test'=>'Ç'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "È"' , 'test'=>'È'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "É"' , 'test'=>'É'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ê"' , 'test'=>'Ê'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ë"' , 'test'=>'Ë'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ì"' , 'test'=>'Ì'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Í"' , 'test'=>'Í'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Î"' , 'test'=>'Î'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ï"' , 'test'=>'Ï'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ð"' , 'test'=>'Ð'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ñ"' , 'test'=>'Ñ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ò"' , 'test'=>'Ò'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ó"' , 'test'=>'Ó'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ô"' , 'test'=>'Ô'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Õ"' , 'test'=>'Õ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ö"' , 'test'=>'Ö'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ø"' , 'test'=>'Ø'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ù"' , 'test'=>'Ù'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ú"' , 'test'=>'Ú'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Û"' , 'test'=>'Û'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ü"' , 'test'=>'Ü'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ý"' , 'test'=>'Ý'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Þ"' , 'test'=>'Þ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                      'getPunycode' => array( 'exception'=>0, 'return' => NULL ),
                        'exception' => 0 )),
);