<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = [
//array( 'label'=>'TEST: "­"' , 'test'=>'­'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '­' ],
                       '__toString' => [ 'exception' => 0, 'return' => '­' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "chr(0x09)"' , 'test'=>'chr(0x09)'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '' ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "chr(0x0B)"' , 'test'=>'chr(0x0B)'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '' ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "chr(0x0A)"' , 'test'=>'chr(0x0A)'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '' ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "chr(0x0D)"' , 'test'=>'chr(0x0D)'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '' ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "chr(0x08)"' , 'test'=>'chr(0x08)'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => chr(0x08) ],
                       '__toString' => [ 'exception' => 0, 'return' => chr(0x08) ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "chr(0x0C)"' , 'test'=>'chr(0x0C)'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => chr(0x0C) ],
                       '__toString' => [ 'exception' => 0, 'return' => chr(0x0C) ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "chr(0x07)"' , 'test'=>'chr(0x07)'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => chr(0x07) ],
                       '__toString' => [ 'exception' => 0, 'return' => chr(0x07) ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "chr(0x1B)"' , 'test'=>'chr(0x1B)'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => chr(0x1B) ],
                       '__toString' => [ 'exception' => 0, 'return' => chr(0x1B) ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "!"' , 'test'=>'!'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '!' ],
                       '__toString' => [ 'exception' => 0, 'return' => '!' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: """' , 'test'=>'"'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '"' ],
                       '__toString' => [ 'exception' => 0, 'return' => '"' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "#"' , 'test'=>'#'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '#' ],
                       '__toString' => [ 'exception' => 0, 'return' => '#' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "%"' , 'test'=>'%'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '%' ],
                       '__toString' => [ 'exception' => 0, 'return' => '%' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "&"' , 'test'=>'&'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '&' ],
                       '__toString' => [ 'exception' => 0, 'return' => '&' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "*"' , 'test'=>'*'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '*' ],
                       '__toString' => [ 'exception' => 0, 'return' => '*' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: ","' , 'test'=>','),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => ',' ],
                       '__toString' => [ 'exception' => 0, 'return' => ',' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "/"' , 'test'=>'/'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '/' ],
                       '__toString' => [ 'exception' => 0, 'return' => '/' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: ":"' , 'test'=>':'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => ':' ],
                       '__toString' => [ 'exception' => 0, 'return' => ':' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: ";"' , 'test'=>';'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => ';' ],
                       '__toString' => [ 'exception' => 0, 'return' => ';' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "?"' , 'test'=>'?'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '?' ],
                       '__toString' => [ 'exception' => 0, 'return' => '?' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "\"' , 'test'=>'\'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '\\' ],
                       '__toString' => [ 'exception' => 0, 'return' => '\\' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¡"' , 'test'=>'¡'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¡' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¡' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "·"' , 'test'=>'·'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '·' ],
                       '__toString' => [ 'exception' => 0, 'return' => '·' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¿"' , 'test'=>'¿'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¿' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¿' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "'"' , 'test'=>'''),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '\'' ],
                       '__toString' => [ 'exception' => 0, 'return' => '\'' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "."' , 'test'=>'.'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '.' ],
                       '__toString' => [ 'exception' => 0, 'return' => '.' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "-"' , 'test'=>'-'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '-' ],
                       '__toString' => [ 'exception' => 0, 'return' => '-' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "("' , 'test'=>'('),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '(' ],
                       '__toString' => [ 'exception' => 0, 'return' => '(' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: ")"' , 'test'=>')'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => ')' ],
                       '__toString' => [ 'exception' => 0, 'return' => ')' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "["' , 'test'=>'['),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '[' ],
                       '__toString' => [ 'exception' => 0, 'return' => '[' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "]"' , 'test'=>']'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => ']' ],
                       '__toString' => [ 'exception' => 0, 'return' => ']' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "{"' , 'test'=>'{'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '{' ],
                       '__toString' => [ 'exception' => 0, 'return' => '{' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "}"' , 'test'=>'}'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '}' ],
                       '__toString' => [ 'exception' => 0, 'return' => '}' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "«"' , 'test'=>'«'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '«' ],
                       '__toString' => [ 'exception' => 0, 'return' => '«' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "»"' , 'test'=>'»'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '»' ],
                       '__toString' => [ 'exception' => 0, 'return' => '»' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "_"' , 'test'=>'_'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '_' ],
                       '__toString' => [ 'exception' => 0, 'return' => '_' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "²"' , 'test'=>'²'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '²' ],
                       '__toString' => [ 'exception' => 0, 'return' => '²' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "³"' , 'test'=>'³'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '³' ],
                       '__toString' => [ 'exception' => 0, 'return' => '³' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¹"' , 'test'=>'¹'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¹' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¹' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¼"' , 'test'=>'¼'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¼' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¼' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "½"' , 'test'=>'½'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '½' ],
                       '__toString' => [ 'exception' => 0, 'return' => '½' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¾"' , 'test'=>'¾'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¾' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¾' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¦"' , 'test'=>'¦'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¦' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¦' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "§"' , 'test'=>'§'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '§' ],
                       '__toString' => [ 'exception' => 0, 'return' => '§' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "©"' , 'test'=>'©'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '©' ],
                       '__toString' => [ 'exception' => 0, 'return' => '©' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "®"' , 'test'=>'®'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '®' ],
                       '__toString' => [ 'exception' => 0, 'return' => '®' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "°"' , 'test'=>'°'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '°' ],
                       '__toString' => [ 'exception' => 0, 'return' => '°' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¶"' , 'test'=>'¶'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¶' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¶' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "^"' , 'test'=>'^'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '^' ],
                       '__toString' => [ 'exception' => 0, 'return' => '^' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "`"' , 'test'=>'`'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '`' ],
                       '__toString' => [ 'exception' => 0, 'return' => '`' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¨"' , 'test'=>'¨'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¨' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¨' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¯"' , 'test'=>'¯'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¯' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¯' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "´"' , 'test'=>'´'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '´' ],
                       '__toString' => [ 'exception' => 0, 'return' => '´' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¸"' , 'test'=>'¸'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¸' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¸' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "$"' , 'test'=>'$'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '$' ],
                       '__toString' => [ 'exception' => 0, 'return' => '$' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¢"' , 'test'=>'¢'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¢' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¢' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "£"' , 'test'=>'£'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '£' ],
                       '__toString' => [ 'exception' => 0, 'return' => '£' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¤"' , 'test'=>'¤'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¤' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¤' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¥"' , 'test'=>'¥'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¥' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¥' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "+"' , 'test'=>'+'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '+' ],
                       '__toString' => [ 'exception' => 0, 'return' => '+' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "<"' , 'test'=>'<'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '<' ],
                       '__toString' => [ 'exception' => 0, 'return' => '<' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "="' , 'test'=>'='),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '=' ],
                       '__toString' => [ 'exception' => 0, 'return' => '=' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: ">"' , 'test'=>'>'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '>' ],
                       '__toString' => [ 'exception' => 0, 'return' => '>' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "|"' , 'test'=>'|'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '|' ],
                       '__toString' => [ 'exception' => 0, 'return' => '|' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "~"' , 'test'=>'~'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '~' ],
                       '__toString' => [ 'exception' => 0, 'return' => '~' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "¬"' , 'test'=>'¬'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '¬' ],
                       '__toString' => [ 'exception' => 0, 'return' => '¬' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "±"' , 'test'=>'±'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '±' ],
                       '__toString' => [ 'exception' => 0, 'return' => '±' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "×"' , 'test'=>'×'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '×' ],
                       '__toString' => [ 'exception' => 0, 'return' => '×' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "÷"' , 'test'=>'÷'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => '÷' ],
                       '__toString' => [ 'exception' => 0, 'return' => '÷' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ª"' , 'test'=>'ª'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ª' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ª' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "µ"' , 'test'=>'µ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'µ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'µ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "º"' , 'test'=>'º'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'º' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'º' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "а"' , 'test'=>'а'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'а' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'а' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "б"' , 'test'=>'б'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'б' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'б' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "в"' , 'test'=>'в'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'в' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'в' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "г"' , 'test'=>'г'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'г' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'г' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "д"' , 'test'=>'д'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'д' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'д' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "е"' , 'test'=>'е'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'е' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'е' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ё"' , 'test'=>'ё'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ё' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ё' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ж"' , 'test'=>'ж'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ж' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ж' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "з"' , 'test'=>'з'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'з' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'з' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "и"' , 'test'=>'и'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'и' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'и' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "й"' , 'test'=>'й'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'й' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'й' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "к"' , 'test'=>'к'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'к' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'к' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "л"' , 'test'=>'л'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'л' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'л' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "м"' , 'test'=>'м'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'м' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'м' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "н"' , 'test'=>'н'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'н' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'н' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "о"' , 'test'=>'о'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'о' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'о' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "п"' , 'test'=>'п'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'п' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'п' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "р"' , 'test'=>'р'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'р' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'р' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "с"' , 'test'=>'с'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'с' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'с' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "т"' , 'test'=>'т'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'т' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'т' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "у"' , 'test'=>'у'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'у' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'у' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ф"' , 'test'=>'ф'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ф' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ф' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "х"' , 'test'=>'х'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'х' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'х' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ц"' , 'test'=>'ц'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ц' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ц' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ч"' , 'test'=>'ч'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ч' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ч' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ш"' , 'test'=>'ш'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ш' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ш' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "щ"' , 'test'=>'щ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'щ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'щ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "э"' , 'test'=>'э'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'э' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'э' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ю"' , 'test'=>'ю'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ю' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ю' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "я"' , 'test'=>'я'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'я' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'я' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ъ"' , 'test'=>'ъ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ъ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ъ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ы"' , 'test'=>'ы'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ы' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ы' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ь"' , 'test'=>'ь'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ь' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ь' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ø"' , 'test'=>'ø'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ø' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ø' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ù"' , 'test'=>'ù'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ù' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ù' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ú"' , 'test'=>'ú'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ú' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ú' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "û"' , 'test'=>'û'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'û' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'û' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ü"' , 'test'=>'ü'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ü' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ü' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ý"' , 'test'=>'ý'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ý' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ý' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "þ"' , 'test'=>'þ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'þ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'þ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ÿ"' , 'test'=>'ÿ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ÿ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ÿ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ß"' , 'test'=>'ß'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ß' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ß' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "à"' , 'test'=>'à'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'à' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'à' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "á"' , 'test'=>'á'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'á' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'á' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "â"' , 'test'=>'â'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'â' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'â' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ã"' , 'test'=>'ã'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ã' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ã' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ä"' , 'test'=>'ä'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ä' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ä' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "å"' , 'test'=>'å'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'å' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'å' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "æ"' , 'test'=>'æ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'æ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'æ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ç"' , 'test'=>'ç'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ç' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ç' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "è"' , 'test'=>'è'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'è' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'è' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "é"' , 'test'=>'é'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'é' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'é' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ê"' , 'test'=>'ê'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ê' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ê' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ë"' , 'test'=>'ë'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ë' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ë' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ì"' , 'test'=>'ì'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ì' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ì' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "í"' , 'test'=>'í'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'í' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'í' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "î"' , 'test'=>'î'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'î' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'î' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ï"' , 'test'=>'ï'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ï' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ï' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ð"' , 'test'=>'ð'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ð' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ð' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ñ"' , 'test'=>'ñ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ñ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ñ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ò"' , 'test'=>'ò'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ò' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ò' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ó"' , 'test'=>'ó'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ó' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ó' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ô"' , 'test'=>'ô'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ô' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ô' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "õ"' , 'test'=>'õ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'õ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'õ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "ö"' , 'test'=>'ö'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'ö' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'ö' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "А"' , 'test'=>'А'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'А' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'А' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Б"' , 'test'=>'Б'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Б' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Б' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "В"' , 'test'=>'В'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'В' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'В' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Г"' , 'test'=>'Г'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Г' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Г' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Д"' , 'test'=>'Д'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Д' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Д' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Е"' , 'test'=>'Е'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Е' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Е' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ё"' , 'test'=>'Ё'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ё' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ё' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ж"' , 'test'=>'Ж'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ж' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ж' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "З"' , 'test'=>'З'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'З' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'З' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "И"' , 'test'=>'И'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'И' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'И' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Й"' , 'test'=>'Й'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Й' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Й' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "К"' , 'test'=>'К'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'К' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'К' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Л"' , 'test'=>'Л'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Л' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Л' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "М"' , 'test'=>'М'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'М' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'М' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Н"' , 'test'=>'Н'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Н' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Н' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "О"' , 'test'=>'О'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'О' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'О' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "П"' , 'test'=>'П'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'П' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'П' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Р"' , 'test'=>'Р'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Р' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Р' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "С"' , 'test'=>'С'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'С' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'С' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Т"' , 'test'=>'Т'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Т' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Т' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "У"' , 'test'=>'У'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'У' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'У' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ф"' , 'test'=>'Ф'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ф' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ф' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Х"' , 'test'=>'Х'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Х' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Х' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ц"' , 'test'=>'Ц'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ц' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ц' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ч"' , 'test'=>'Ч'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ч' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ч' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ш"' , 'test'=>'Ш'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ш' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ш' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Щ"' , 'test'=>'Щ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Щ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Щ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Э"' , 'test'=>'Э'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Э' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Э' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ю"' , 'test'=>'Ю'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ю' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ю' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Я"' , 'test'=>'Я'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Я' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Я' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ъ"' , 'test'=>'Ъ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ъ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ъ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ы"' , 'test'=>'Ы'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ы' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ы' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ь"' , 'test'=>'Ь'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ь' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ь' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "À"' , 'test'=>'À'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'À' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'À' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Á"' , 'test'=>'Á'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Á' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Á' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Â"' , 'test'=>'Â'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Â' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Â' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ã"' , 'test'=>'Ã'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ã' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ã' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ä"' , 'test'=>'Ä'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ä' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ä' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Å"' , 'test'=>'Å'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Å' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Å' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Æ"' , 'test'=>'Æ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Æ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Æ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ç"' , 'test'=>'Ç'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ç' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ç' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "È"' , 'test'=>'È'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'È' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'È' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "É"' , 'test'=>'É'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'É' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'É' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ê"' , 'test'=>'Ê'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ê' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ê' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ë"' , 'test'=>'Ë'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ë' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ë' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ì"' , 'test'=>'Ì'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ì' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ì' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Í"' , 'test'=>'Í'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Í' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Í' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Î"' , 'test'=>'Î'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Î' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Î' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ï"' , 'test'=>'Ï'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ï' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ï' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ð"' , 'test'=>'Ð'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ð' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ð' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ñ"' , 'test'=>'Ñ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ñ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ñ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ò"' , 'test'=>'Ò'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ò' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ò' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ó"' , 'test'=>'Ó'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ó' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ó' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ô"' , 'test'=>'Ô'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ô' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ô' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Õ"' , 'test'=>'Õ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Õ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Õ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ö"' , 'test'=>'Ö'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ö' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ö' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ø"' , 'test'=>'Ø'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ø' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ø' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ù"' , 'test'=>'Ù'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ù' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ù' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ú"' , 'test'=>'Ú'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ú' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ú' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Û"' , 'test'=>'Û'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Û' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Û' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ü"' , 'test'=>'Ü'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ü' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ü' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Ý"' , 'test'=>'Ý'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Ý' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Ý' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
//array( 'label'=>'TEST: "Þ"' , 'test'=>'Þ'),
[ 'expected' => [ 'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 'Þ' ],
                       '__toString' => [ 'exception' => 0, 'return' => 'Þ' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ],
                        'exception' => 0 ]],
];
