<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = array(
//array( 'label'=>'TEST: "­"' , 'test'=>'­'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '­' ),
                       '__toString' => array( 'exception'=>0, 'return' => '­' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x09)"' , 'test'=>'chr(0x09)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '' ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x0B)"' , 'test'=>'chr(0x0B)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '' ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x0A)"' , 'test'=>'chr(0x0A)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '' ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x0D)"' , 'test'=>'chr(0x0D)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '' ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x08)"' , 'test'=>'chr(0x08)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => chr(0x08) ),
                       '__toString' => array( 'exception'=>0, 'return' => chr(0x08) ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x0C)"' , 'test'=>'chr(0x0C)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => chr(0x0C) ),
                       '__toString' => array( 'exception'=>0, 'return' => chr(0x0C) ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x07)"' , 'test'=>'chr(0x07)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => chr(0x07) ),
                       '__toString' => array( 'exception'=>0, 'return' => chr(0x07) ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "chr(0x1B)"' , 'test'=>'chr(0x1B)'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => chr(0x1B) ),
                       '__toString' => array( 'exception'=>0, 'return' => chr(0x1B) ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "!"' , 'test'=>'!'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '!' ),
                       '__toString' => array( 'exception'=>0, 'return' => '!' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: """' , 'test'=>'"'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '"' ),
                       '__toString' => array( 'exception'=>0, 'return' => '"' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "#"' , 'test'=>'#'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '#' ),
                       '__toString' => array( 'exception'=>0, 'return' => '#' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "%"' , 'test'=>'%'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '%' ),
                       '__toString' => array( 'exception'=>0, 'return' => '%' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "&"' , 'test'=>'&'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '&' ),
                       '__toString' => array( 'exception'=>0, 'return' => '&' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "*"' , 'test'=>'*'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '*' ),
                       '__toString' => array( 'exception'=>0, 'return' => '*' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ","' , 'test'=>','),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => ',' ),
                       '__toString' => array( 'exception'=>0, 'return' => ',' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "/"' , 'test'=>'/'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '/' ),
                       '__toString' => array( 'exception'=>0, 'return' => '/' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ":"' , 'test'=>':'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => ':' ),
                       '__toString' => array( 'exception'=>0, 'return' => ':' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ";"' , 'test'=>';'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => ';' ),
                       '__toString' => array( 'exception'=>0, 'return' => ';' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "?"' , 'test'=>'?'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '?' ),
                       '__toString' => array( 'exception'=>0, 'return' => '?' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "\"' , 'test'=>'\'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '\\' ),
                       '__toString' => array( 'exception'=>0, 'return' => '\\' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¡"' , 'test'=>'¡'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¡' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¡' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "·"' , 'test'=>'·'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '·' ),
                       '__toString' => array( 'exception'=>0, 'return' => '·' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¿"' , 'test'=>'¿'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¿' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¿' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "'"' , 'test'=>'''),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '\'' ),
                       '__toString' => array( 'exception'=>0, 'return' => '\'' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "."' , 'test'=>'.'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '.' ),
                       '__toString' => array( 'exception'=>0, 'return' => '.' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "-"' , 'test'=>'-'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '-' ),
                       '__toString' => array( 'exception'=>0, 'return' => '-' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "("' , 'test'=>'('),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '(' ),
                       '__toString' => array( 'exception'=>0, 'return' => '(' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ")"' , 'test'=>')'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => ')' ),
                       '__toString' => array( 'exception'=>0, 'return' => ')' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "["' , 'test'=>'['),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '[' ),
                       '__toString' => array( 'exception'=>0, 'return' => '[' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "]"' , 'test'=>']'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => ']' ),
                       '__toString' => array( 'exception'=>0, 'return' => ']' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "{"' , 'test'=>'{'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '{' ),
                       '__toString' => array( 'exception'=>0, 'return' => '{' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "}"' , 'test'=>'}'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '}' ),
                       '__toString' => array( 'exception'=>0, 'return' => '}' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "«"' , 'test'=>'«'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '«' ),
                       '__toString' => array( 'exception'=>0, 'return' => '«' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "»"' , 'test'=>'»'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '»' ),
                       '__toString' => array( 'exception'=>0, 'return' => '»' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "_"' , 'test'=>'_'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '_' ),
                       '__toString' => array( 'exception'=>0, 'return' => '_' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "²"' , 'test'=>'²'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '²' ),
                       '__toString' => array( 'exception'=>0, 'return' => '²' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "³"' , 'test'=>'³'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '³' ),
                       '__toString' => array( 'exception'=>0, 'return' => '³' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¹"' , 'test'=>'¹'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¹' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¹' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¼"' , 'test'=>'¼'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¼' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¼' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "½"' , 'test'=>'½'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '½' ),
                       '__toString' => array( 'exception'=>0, 'return' => '½' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¾"' , 'test'=>'¾'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¾' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¾' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¦"' , 'test'=>'¦'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¦' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¦' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "§"' , 'test'=>'§'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '§' ),
                       '__toString' => array( 'exception'=>0, 'return' => '§' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "©"' , 'test'=>'©'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '©' ),
                       '__toString' => array( 'exception'=>0, 'return' => '©' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "®"' , 'test'=>'®'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '®' ),
                       '__toString' => array( 'exception'=>0, 'return' => '®' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "°"' , 'test'=>'°'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '°' ),
                       '__toString' => array( 'exception'=>0, 'return' => '°' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¶"' , 'test'=>'¶'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¶' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¶' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "^"' , 'test'=>'^'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '^' ),
                       '__toString' => array( 'exception'=>0, 'return' => '^' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "`"' , 'test'=>'`'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '`' ),
                       '__toString' => array( 'exception'=>0, 'return' => '`' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¨"' , 'test'=>'¨'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¨' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¨' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¯"' , 'test'=>'¯'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¯' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¯' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "´"' , 'test'=>'´'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '´' ),
                       '__toString' => array( 'exception'=>0, 'return' => '´' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¸"' , 'test'=>'¸'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¸' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¸' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "$"' , 'test'=>'$'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '$' ),
                       '__toString' => array( 'exception'=>0, 'return' => '$' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¢"' , 'test'=>'¢'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¢' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¢' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "£"' , 'test'=>'£'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '£' ),
                       '__toString' => array( 'exception'=>0, 'return' => '£' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¤"' , 'test'=>'¤'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¤' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¤' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¥"' , 'test'=>'¥'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¥' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¥' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "+"' , 'test'=>'+'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '+' ),
                       '__toString' => array( 'exception'=>0, 'return' => '+' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "<"' , 'test'=>'<'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '<' ),
                       '__toString' => array( 'exception'=>0, 'return' => '<' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "="' , 'test'=>'='),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '=' ),
                       '__toString' => array( 'exception'=>0, 'return' => '=' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: ">"' , 'test'=>'>'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '>' ),
                       '__toString' => array( 'exception'=>0, 'return' => '>' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "|"' , 'test'=>'|'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '|' ),
                       '__toString' => array( 'exception'=>0, 'return' => '|' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "~"' , 'test'=>'~'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '~' ),
                       '__toString' => array( 'exception'=>0, 'return' => '~' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "¬"' , 'test'=>'¬'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '¬' ),
                       '__toString' => array( 'exception'=>0, 'return' => '¬' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "±"' , 'test'=>'±'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '±' ),
                       '__toString' => array( 'exception'=>0, 'return' => '±' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "×"' , 'test'=>'×'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '×' ),
                       '__toString' => array( 'exception'=>0, 'return' => '×' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "÷"' , 'test'=>'÷'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => '÷' ),
                       '__toString' => array( 'exception'=>0, 'return' => '÷' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ª"' , 'test'=>'ª'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ª' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ª' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "µ"' , 'test'=>'µ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'µ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'µ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "º"' , 'test'=>'º'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'º' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'º' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "а"' , 'test'=>'а'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'а' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'а' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "б"' , 'test'=>'б'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'б' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'б' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "в"' , 'test'=>'в'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'в' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'в' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "г"' , 'test'=>'г'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'г' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'г' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "д"' , 'test'=>'д'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'д' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'д' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "е"' , 'test'=>'е'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'е' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'е' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ё"' , 'test'=>'ё'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ё' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ё' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ж"' , 'test'=>'ж'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ж' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ж' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "з"' , 'test'=>'з'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'з' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'з' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "и"' , 'test'=>'и'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'и' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'и' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "й"' , 'test'=>'й'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'й' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'й' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "к"' , 'test'=>'к'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'к' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'к' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "л"' , 'test'=>'л'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'л' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'л' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "м"' , 'test'=>'м'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'м' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'м' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "н"' , 'test'=>'н'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'н' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'н' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "о"' , 'test'=>'о'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'о' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'о' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "п"' , 'test'=>'п'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'п' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'п' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "р"' , 'test'=>'р'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'р' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'р' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "с"' , 'test'=>'с'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'с' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'с' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "т"' , 'test'=>'т'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'т' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'т' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "у"' , 'test'=>'у'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'у' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'у' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ф"' , 'test'=>'ф'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ф' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ф' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "х"' , 'test'=>'х'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'х' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'х' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ц"' , 'test'=>'ц'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ц' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ц' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ч"' , 'test'=>'ч'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ч' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ч' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ш"' , 'test'=>'ш'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ш' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ш' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "щ"' , 'test'=>'щ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'щ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'щ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "э"' , 'test'=>'э'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'э' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'э' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ю"' , 'test'=>'ю'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ю' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ю' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "я"' , 'test'=>'я'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'я' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'я' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ъ"' , 'test'=>'ъ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ъ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ъ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ы"' , 'test'=>'ы'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ы' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ы' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ь"' , 'test'=>'ь'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ь' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ь' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ø"' , 'test'=>'ø'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ø' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ø' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ù"' , 'test'=>'ù'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ù' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ù' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ú"' , 'test'=>'ú'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ú' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ú' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "û"' , 'test'=>'û'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'û' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'û' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ü"' , 'test'=>'ü'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ü' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ü' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ý"' , 'test'=>'ý'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ý' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ý' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "þ"' , 'test'=>'þ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'þ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'þ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ÿ"' , 'test'=>'ÿ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ÿ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ÿ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ß"' , 'test'=>'ß'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ß' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ß' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "à"' , 'test'=>'à'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'à' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'à' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "á"' , 'test'=>'á'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'á' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'á' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "â"' , 'test'=>'â'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'â' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'â' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ã"' , 'test'=>'ã'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ã' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ã' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ä"' , 'test'=>'ä'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ä' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ä' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "å"' , 'test'=>'å'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'å' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'å' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "æ"' , 'test'=>'æ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'æ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'æ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ç"' , 'test'=>'ç'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ç' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ç' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "è"' , 'test'=>'è'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'è' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'è' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "é"' , 'test'=>'é'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'é' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'é' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ê"' , 'test'=>'ê'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ê' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ê' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ë"' , 'test'=>'ë'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ë' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ë' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ì"' , 'test'=>'ì'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ì' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ì' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "í"' , 'test'=>'í'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'í' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'í' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "î"' , 'test'=>'î'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'î' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'î' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ï"' , 'test'=>'ï'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ï' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ï' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ð"' , 'test'=>'ð'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ð' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ð' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ñ"' , 'test'=>'ñ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ñ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ñ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ò"' , 'test'=>'ò'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ò' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ò' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ó"' , 'test'=>'ó'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ó' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ó' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ô"' , 'test'=>'ô'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ô' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ô' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "õ"' , 'test'=>'õ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'õ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'õ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "ö"' , 'test'=>'ö'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'ö' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'ö' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "А"' , 'test'=>'А'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'А' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'А' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Б"' , 'test'=>'Б'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Б' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Б' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "В"' , 'test'=>'В'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'В' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'В' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Г"' , 'test'=>'Г'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Г' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Г' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Д"' , 'test'=>'Д'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Д' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Д' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Е"' , 'test'=>'Е'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Е' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Е' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ё"' , 'test'=>'Ё'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ё' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ё' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ж"' , 'test'=>'Ж'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ж' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ж' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "З"' , 'test'=>'З'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'З' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'З' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "И"' , 'test'=>'И'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'И' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'И' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Й"' , 'test'=>'Й'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Й' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Й' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "К"' , 'test'=>'К'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'К' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'К' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Л"' , 'test'=>'Л'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Л' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Л' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "М"' , 'test'=>'М'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'М' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'М' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Н"' , 'test'=>'Н'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Н' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Н' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "О"' , 'test'=>'О'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'О' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'О' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "П"' , 'test'=>'П'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'П' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'П' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Р"' , 'test'=>'Р'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Р' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Р' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "С"' , 'test'=>'С'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'С' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'С' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Т"' , 'test'=>'Т'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Т' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Т' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "У"' , 'test'=>'У'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'У' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'У' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ф"' , 'test'=>'Ф'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ф' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ф' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Х"' , 'test'=>'Х'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Х' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Х' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ц"' , 'test'=>'Ц'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ц' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ц' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ч"' , 'test'=>'Ч'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ч' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ч' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ш"' , 'test'=>'Ш'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ш' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ш' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Щ"' , 'test'=>'Щ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Щ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Щ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Э"' , 'test'=>'Э'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Э' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Э' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ю"' , 'test'=>'Ю'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ю' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ю' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Я"' , 'test'=>'Я'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Я' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Я' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ъ"' , 'test'=>'Ъ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ъ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ъ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ы"' , 'test'=>'Ы'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ы' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ы' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ь"' , 'test'=>'Ь'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ь' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ь' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "À"' , 'test'=>'À'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'À' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'À' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Á"' , 'test'=>'Á'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Á' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Á' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Â"' , 'test'=>'Â'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Â' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Â' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ã"' , 'test'=>'Ã'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ã' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ã' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ä"' , 'test'=>'Ä'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ä' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ä' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Å"' , 'test'=>'Å'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Å' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Å' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Æ"' , 'test'=>'Æ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Æ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Æ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ç"' , 'test'=>'Ç'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ç' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ç' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "È"' , 'test'=>'È'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'È' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'È' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "É"' , 'test'=>'É'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'É' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'É' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ê"' , 'test'=>'Ê'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ê' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ê' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ë"' , 'test'=>'Ë'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ë' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ë' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ì"' , 'test'=>'Ì'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ì' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ì' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Í"' , 'test'=>'Í'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Í' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Í' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Î"' , 'test'=>'Î'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Î' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Î' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ï"' , 'test'=>'Ï'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ï' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ï' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ð"' , 'test'=>'Ð'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ð' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ð' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ñ"' , 'test'=>'Ñ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ñ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ñ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ò"' , 'test'=>'Ò'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ò' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ò' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ó"' , 'test'=>'Ó'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ó' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ó' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ô"' , 'test'=>'Ô'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ô' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ô' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Õ"' , 'test'=>'Õ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Õ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Õ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ö"' , 'test'=>'Ö'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ö' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ö' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ø"' , 'test'=>'Ø'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ø' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ø' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ù"' , 'test'=>'Ù'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ù' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ù' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ú"' , 'test'=>'Ú'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ú' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ú' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Û"' , 'test'=>'Û'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Û' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Û' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ü"' , 'test'=>'Ü'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ü' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ü' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Ý"' , 'test'=>'Ý'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Ý' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Ý' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
//array( 'label'=>'TEST: "Þ"' , 'test'=>'Þ'),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 'Þ' ),
                       '__toString' => array( 'exception'=>0, 'return' => 'Þ' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        'exception' => 0 )),
);
