<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = [
//array( 'label'=>'TEST: "­"' , 'test'=>'­'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "chr(0x09)"' , 'test'=>'chr(0x09)'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "chr(0x0B)"' , 'test'=>'chr(0x0B)'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "chr(0x0A)"' , 'test'=>'chr(0x0A)'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "chr(0x0D)"' , 'test'=>'chr(0x0D)'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "chr(0x08)"' , 'test'=>'chr(0x08)'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "chr(0x0C)"' , 'test'=>'chr(0x0C)'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "chr(0x07)"' , 'test'=>'chr(0x07)'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "chr(0x1B)"' , 'test'=>'chr(0x1B)'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "!"' , 'test'=>'!'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: """' , 'test'=>'"'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "#"' , 'test'=>'#'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "%"' , 'test'=>'%'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "&"' , 'test'=>'&'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "*"' , 'test'=>'*'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: ","' , 'test'=>','),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "/"' , 'test'=>'/'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: ":"' , 'test'=>':'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: ";"' , 'test'=>';'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "?"' , 'test'=>'?'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "\"' , 'test'=>'\'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¡"' , 'test'=>'¡'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "·"' , 'test'=>'·'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¿"' , 'test'=>'¿'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "'"' , 'test'=>'''),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "."' , 'test'=>'.'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "-"' , 'test'=>'-'),!!!
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "("' , 'test'=>'('),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: ")"' , 'test'=>')'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "["' , 'test'=>'['),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "]"' , 'test'=>']'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "{"' , 'test'=>'{'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "}"' , 'test'=>'}'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "«"' , 'test'=>'«'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "»"' , 'test'=>'»'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "_"' , 'test'=>'_'), !!!
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "²"' , 'test'=>'²'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "³"' , 'test'=>'³'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¹"' , 'test'=>'¹'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¼"' , 'test'=>'¼'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "½"' , 'test'=>'½'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¾"' , 'test'=>'¾'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¦"' , 'test'=>'¦'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "§"' , 'test'=>'§'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "©"' , 'test'=>'©'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "®"' , 'test'=>'®'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "°"' , 'test'=>'°'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¶"' , 'test'=>'¶'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "^"' , 'test'=>'^'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "`"' , 'test'=>'`'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¨"' , 'test'=>'¨'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¯"' , 'test'=>'¯'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "´"' , 'test'=>'´'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¸"' , 'test'=>'¸'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "$"' , 'test'=>'$'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¢"' , 'test'=>'¢'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "£"' , 'test'=>'£'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¤"' , 'test'=>'¤'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¥"' , 'test'=>'¥'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "+"' , 'test'=>'+'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "<"' , 'test'=>'<'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "="' , 'test'=>'='),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: ">"' , 'test'=>'>'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "|"' , 'test'=>'|'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "~"' , 'test'=>'~'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "¬"' , 'test'=>'¬'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "±"' , 'test'=>'±'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "×"' , 'test'=>'×'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "÷"' , 'test'=>'÷'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ª"' , 'test'=>'ª'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "µ"' , 'test'=>'µ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "º"' , 'test'=>'º'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "а"' , 'test'=>'а'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "б"' , 'test'=>'б'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "в"' , 'test'=>'в'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "г"' , 'test'=>'г'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "д"' , 'test'=>'д'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "е"' , 'test'=>'е'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ё"' , 'test'=>'ё'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ж"' , 'test'=>'ж'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "з"' , 'test'=>'з'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "и"' , 'test'=>'и'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "й"' , 'test'=>'й'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "к"' , 'test'=>'к'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "л"' , 'test'=>'л'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "м"' , 'test'=>'м'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "н"' , 'test'=>'н'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "о"' , 'test'=>'о'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "п"' , 'test'=>'п'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "р"' , 'test'=>'р'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "с"' , 'test'=>'с'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "т"' , 'test'=>'т'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "у"' , 'test'=>'у'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ф"' , 'test'=>'ф'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "х"' , 'test'=>'х'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ц"' , 'test'=>'ц'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ч"' , 'test'=>'ч'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ш"' , 'test'=>'ш'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "щ"' , 'test'=>'щ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "э"' , 'test'=>'э'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ю"' , 'test'=>'ю'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "я"' , 'test'=>'я'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ъ"' , 'test'=>'ъ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ы"' , 'test'=>'ы'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ь"' , 'test'=>'ь'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ø"' , 'test'=>'ø'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ù"' , 'test'=>'ù'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ú"' , 'test'=>'ú'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "û"' , 'test'=>'û'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ü"' , 'test'=>'ü'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ý"' , 'test'=>'ý'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "þ"' , 'test'=>'þ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ÿ"' , 'test'=>'ÿ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ß"' , 'test'=>'ß'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "à"' , 'test'=>'à'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "á"' , 'test'=>'á'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "â"' , 'test'=>'â'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ã"' , 'test'=>'ã'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ä"' , 'test'=>'ä'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "å"' , 'test'=>'å'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "æ"' , 'test'=>'æ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ç"' , 'test'=>'ç'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "è"' , 'test'=>'è'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "é"' , 'test'=>'é'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ê"' , 'test'=>'ê'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ë"' , 'test'=>'ë'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ì"' , 'test'=>'ì'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "í"' , 'test'=>'í'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "î"' , 'test'=>'î'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ï"' , 'test'=>'ï'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ð"' , 'test'=>'ð'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ñ"' , 'test'=>'ñ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ò"' , 'test'=>'ò'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ó"' , 'test'=>'ó'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ô"' , 'test'=>'ô'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "õ"' , 'test'=>'õ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "ö"' , 'test'=>'ö'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "А"' , 'test'=>'А'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Б"' , 'test'=>'Б'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "В"' , 'test'=>'В'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Г"' , 'test'=>'Г'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Д"' , 'test'=>'Д'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Е"' , 'test'=>'Е'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ё"' , 'test'=>'Ё'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ж"' , 'test'=>'Ж'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "З"' , 'test'=>'З'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "И"' , 'test'=>'И'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Й"' , 'test'=>'Й'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "К"' , 'test'=>'К'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Л"' , 'test'=>'Л'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "М"' , 'test'=>'М'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Н"' , 'test'=>'Н'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "О"' , 'test'=>'О'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "П"' , 'test'=>'П'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Р"' , 'test'=>'Р'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "С"' , 'test'=>'С'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Т"' , 'test'=>'Т'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "У"' , 'test'=>'У'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ф"' , 'test'=>'Ф'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Х"' , 'test'=>'Х'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ц"' , 'test'=>'Ц'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ч"' , 'test'=>'Ч'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ш"' , 'test'=>'Ш'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Щ"' , 'test'=>'Щ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Э"' , 'test'=>'Э'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ю"' , 'test'=>'Ю'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Я"' , 'test'=>'Я'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ъ"' , 'test'=>'Ъ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ы"' , 'test'=>'Ы'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ь"' , 'test'=>'Ь'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "À"' , 'test'=>'À'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Á"' , 'test'=>'Á'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Â"' , 'test'=>'Â'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ã"' , 'test'=>'Ã'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ä"' , 'test'=>'Ä'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Å"' , 'test'=>'Å'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Æ"' , 'test'=>'Æ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ç"' , 'test'=>'Ç'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "È"' , 'test'=>'È'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "É"' , 'test'=>'É'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ê"' , 'test'=>'Ê'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ë"' , 'test'=>'Ë'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ì"' , 'test'=>'Ì'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Í"' , 'test'=>'Í'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Î"' , 'test'=>'Î'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ï"' , 'test'=>'Ï'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ð"' , 'test'=>'Ð'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ñ"' , 'test'=>'Ñ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ò"' , 'test'=>'Ò'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ó"' , 'test'=>'Ó'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ô"' , 'test'=>'Ô'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Õ"' , 'test'=>'Õ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ö"' , 'test'=>'Ö'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ø"' , 'test'=>'Ø'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ù"' , 'test'=>'Ù'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ú"' , 'test'=>'Ú'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Û"' , 'test'=>'Û'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ü"' , 'test'=>'Ü'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Ý"' , 'test'=>'Ý'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
//array( 'label'=>'TEST: "Þ"' , 'test'=>'Þ'),
[ 'expected' => [ 'exception' => 3 ],
                          'construct' => [ 'exception' => 3, 'return' => null ],
                              'write' => [ 'exception' => 0, 'return' => null ],],
];
