<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = array(
//array( 'label'=>'TEST: integer 0'                       , 'test'=>0),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 0 ),
                       '__toString' => array( 'exception'=>0, 'return' => '0' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        )),
//array( 'label'=>'TEST: decimal number 1234'             , 'test'=>1234),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 1234 ),
                       '__toString' => array( 'exception'=>0, 'return' => '1234' ),
                        'getLength' => array( 'exception'=>0, 'return' => 4 ),
                        )),
//array( 'label'=>'TEST: negative integer -123'           , 'test'=>-123),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -123 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-123' ),
                        'getLength' => array( 'exception'=>0, 'return' => 4 ),
                        )),
//array( 'label'=>'TEST: octal number 0123 (83)'          , 'test'=>0123),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 83 ),
                       '__toString' => array( 'exception'=>0, 'return' => '83' ),
                        'getLength' => array( 'exception'=>0, 'return' => 2 ),
                        )),
//array( 'label'=>'TEST: hexadecimal number 0x1A (26)'    , 'test'=>0x1A),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 26 ),
                       '__toString' => array( 'exception'=>0, 'return' => '26' ),
                        'getLength' => array( 'exception'=>0, 'return' => 2 ),
                        )),
//array( 'label'=>'TEST: float 0.0'                       , 'test'=>0.0),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 0.0 ),
                       '__toString' => array( 'exception'=>0, 'return' => '0' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        )),
//array( 'label'=>'TEST: float 3.5714285714286'           , 'test'=>25/7),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 3.5714285714286 ),
                       '__toString' => array( 'exception'=>0, 'return' => '3.5714285714286' ),
                        'getLength' => array( 'exception'=>0, 'return' => 15 ),
                        )),
//array( 'label'=>'TEST: double 1.1258999068426E+15'      , 'test'=>pow(2,50)),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 1125899906842624),
                       '__toString' => array( 'exception'=>0, 'return' => '1.1258999068426E+15' ),
                        'getLength' => array( 'exception'=>0, 'return' => 19 ),
                        )),
//array( 'label'=>'TEST: real 7E-10'                      , 'test'=>7E-10),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 7.0E-10 ),
                       '__toString' => array( 'exception'=>0, 'return' => '7.0E-10' ),
                        'getLength' => array( 'exception'=>0, 'return' => 7 ),
                        )),
//array( 'label'=>'TEST: range 2147483647'                , 'test'=>2147483647),
array( 'expected'=>array( 'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 2147483647 ),
                       '__toString' => array( 'exception'=>0, 'return' => '2147483647' ),
                        'getLength' => array( 'exception'=>0, 'return' => 10 ),
                        )),
//array( 'label'=>'TEST: range -2147483648'               , 'test'=>-2147483648),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -2147483648 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-2147483648' ),
                        'getLength' => array( 'exception'=>0, 'return' => 11 ),
                        )),
//array( 'label'=>'TEST: range 2147483648'                , 'test'=>2147483648 ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 2147483648 ),
                       '__toString' => array( 'exception'=>0, 'return' => '2147483648' ),
                        'getLength' => array( 'exception'=>0, 'return' => 10 ),
                        )),
//array( 'label'=>'TEST: range -2147483649'               , 'test'=>-2147483649 ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -2147483649 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-2147483649' ),
                        'getLength' => array( 'exception'=>0, 'return' => 11 ),
                        )),
//array( 'label'=>'TEST: range 9223372036854775807'       , 'test'=>9.2233720368548E+18 ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 9223372036854775807 ),
                       '__toString' => array( 'exception'=>0, 'return' => '9.2233720368548E+18' ),
                        'getLength' => array( 'exception'=>0, 'return' => 19 ),
                        )),
//array( 'label'=>'TEST: range -9223372036854775808'      , 'test'=>-9.2233720368548E+18 ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -9223372036854775808 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-9.2233720368548E+18' ),
                        'getLength' => array( 'exception'=>0, 'return' => 20 ),
                        )),
//array( 'label'=>'TEST: range 9223372036854775808'       , 'test'=>9223372036854775808 ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 9223372036854775807 ),
                       '__toString' => array( 'exception'=>0, 'return' => '9.2233720368548E+18' ),
                        'getLength' => array( 'exception'=>0, 'return' => 19 ),
                        )),
//array( 'label'=>'TEST: range -9223372036854775809'      , 'test'=>-9223372036854775809 ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -9223372036854775808 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-9.2233720368548E+18' ),
                        'getLength' => array( 'exception'=>0, 'return' => 20 ),
                        )),
);