<?php
$this->_aTests[self::KEY_TEST] = [
['label' => 'Test 01', 'test' => [ 'value' => 5.0,  'min' => null,  'max' => null ] ],
['label' => 'Test 02', 'test' => [ 'value' => 5.0,  'min' => 0.0,   'max' => null ] ],
['label' => 'Test 03', 'test' => [ 'value' => 5.0,  'min' => null,  'max' => 10.0 ] ],
['label' => 'Test 04', 'test' => [ 'value' => 5.0,  'min' => 0.0,   'max' => 10.0 ] ],
['label' => 'Test 05', 'test' => [ 'value' => 5.0,  'min' => 6.0,   'max' => null ] ],
['label' => 'Test 06', 'test' => [ 'value' => 5.0,  'min' => null,  'max' => 4.0  ] ],
['label' => 'Test 07', 'test' => [ 'value' => 5.0,  'min' => 1.0,   'max' => 2.0  ] ],
['label' => 'Test 08', 'test' => [ 'value' => -5.0, 'min' => null,  'max' => null ] ],
['label' => 'Test 09', 'test' => [ 'value' => -5.0, 'min' => -10.0, 'max' => null ] ],
['label' => 'Test 10', 'test' => [ 'value' => -5.0, 'min' => null,  'max' => 0.0  ] ],
['label' => 'Test 11', 'test' => [ 'value' => -5.0, 'min' => -10.0, 'max' => 0.0  ] ],
['label' => 'Test 12', 'test' => [ 'value' => -5.0, 'min' => -4.0,  'max' => null ] ],
['label' => 'Test 13', 'test' => [ 'value' => -5.0, 'min' => null,  'max' => -6.0 ] ],
['label' => 'Test 14', 'test' => [ 'value' => -5.0, 'min' => -2.0,  'max' => -1.0 ] ],
['label' => 'Test 15', 'test' => [ 'value' => 0.0,  'min' => 0.0,   'max' => null ] ],
['label' => 'Test 16', 'test' => [ 'value' => 0.0,  'min' => null,  'max' => 0.0  ] ],
['label' => 'Test 17', 'test' => [ 'value' => 0.0,  'min' => 0.0,   'max' => 0.0  ] ],
];
