<?php
if( PHP_INT_MAX>2147483647 )
{
    //64bit
    $aBuffer32= array( 'max' => array(  'i' => 2147483647,  's' => '2147483647' ),
                       'min' => array(  'i' => (int)-2147483648, 's' => '-2147483648' ),
                       'maxo' => array( 'i' => 2147483648,  's' => '2147483648' ),
                       'mino' => array( 'i' => -2147483649, 's' => '-2147483649' ),
    );
    $aBuffer64= array( 'max' => array(  'i' => 9223372036854775807,  's' => '9223372036854775807' ),
                       'min' => array(  'i' => -9223372036854775808, 's' => '-9223372036854775808' ),
                       'maxo' => array( 'i' => -9223372036854775808,  's' => '-9223372036854775808' ),
                       'mino' => array( 'i' => 9223372036854775807, 's' => '9223372036854775807' ),
    );
}
else
{
    //32bit
    $aBuffer32= array( 'max' => array(  'i' => 2147483647,  's' => '2147483647' ),
                       'min' => array(  'i' => (int)-2147483648, 's' => '-2147483648' ),
                       'maxo' => array( 'i' => (int)-2147483648,  's' => '-2147483648' ),
                       'mino' => array( 'i' => 2147483647, 's' => '2147483647' ),
    );
    $aBuffer64= array( 'max' => array(  'i' => 0, 's' => '0' ),
                       'min' => array(  'i' => 0, 's' => '0' ),
                       'maxo' => array( 'i' => 0, 's' => '0' ),
                       'mino' => array( 'i' => 0, 's' => '0' ),
    );

}

// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = array(
//array( 'label'=>'TEST: integer 0'                       , 'test'=>'0'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 0 ),
                       '__toString' => array( 'exception'=>0, 'return' => '0' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        )),
//array( 'label'=>'TEST: decimal number 1234'             , 'test'=>'1234'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 1234 ),
                       '__toString' => array( 'exception'=>0, 'return' => '1234' ),
                        'getLength' => array( 'exception'=>0, 'return' => 4 ),
                        )),
//array( 'label'=>'TEST: negative integer -123'           , 'test'=>'-123'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => -123 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-123' ),
                        'getLength' => array( 'exception'=>0, 'return' => 4 ),
                        )),
//array( 'label'=>'TEST: octal number 0123 (83)'          , 'test'=>'0123'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 123 ),
                       '__toString' => array( 'exception'=>0, 'return' => '123' ),
                        'getLength' => array( 'exception'=>0, 'return' => 3 ),
                        )),
//array( 'label'=>'TEST: hexadecimal number 0x1A (26)'    , 'test'=>'0x1A'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 26 ),
                       '__toString' => array( 'exception'=>0, 'return' => '26' ),
                        'getLength' => array( 'exception'=>0, 'return' => 2 ),
                        )),
//array( 'label'=>'TEST: float 0.0'                       , 'test'=>'0.0'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 0 ),
                       '__toString' => array( 'exception'=>0, 'return' => '0' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        )),
//array( 'label'=>'TEST: float 3.5714285714286'           , 'test'=>'3.5714285714286'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 3 ),
                       '__toString' => array( 'exception'=>0, 'return' => '3' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        )),
//array( 'label'=>'TEST: double 1.1258999068426E+15'      , 'test'=>'1125899906842624'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 0),
                       '__toString' => array( 'exception'=>0, 'return' => '0' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        )),
//array( 'label'=>'TEST: real 7E-10'                      , 'test'=>'7E-10'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 0 ),
                       '__toString' => array( 'exception'=>0, 'return' => '0' ),
                        'getLength' => array( 'exception'=>0, 'return' => 1 ),
                        )),
//array( 'label'=>'TEST: range 2147483647'                , 'test'=>'2147483647'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => 2147483647 ),
                       '__toString' => array( 'exception'=>0, 'return' => '2147483647' ),
                        'getLength' => array( 'exception'=>0, 'return' => 10 ),
                        )),
//array( 'label'=>'TEST: range -2147483648'               , 'test'=>'-2147483648'),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => (int)-2147483648 ),
                       '__toString' => array( 'exception'=>0, 'return' => '-2147483648' ),
                        'getLength' => array( 'exception'=>0, 'return' => 11 ),
                        )),
//array( 'label'=>'TEST: range 2147483648'                , 'test'=>'2147483648' ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => $aBuffer32['maxo']['i'] ),
                       '__toString' => array( 'exception'=>0, 'return' => $aBuffer32['maxo']['s'] ),
                        'getLength' => array( 'exception'=>0, 'return' => strlen($aBuffer32['maxo']['s']) ),
                        )),
//array( 'label'=>'TEST: range -2147483649'               , 'test'=>'-2147483649' ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => $aBuffer32['mino']['i'] ),
                       '__toString' => array( 'exception'=>0, 'return' => $aBuffer32['mino']['s'] ),
                        'getLength' => array( 'exception'=>0, 'return' => strlen($aBuffer32['mino']['s']) ),
                        )),
//array( 'label'=>'TEST: range 9223372036854775807'       , 'test'=>'9223372036854775807' ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => $aBuffer64['max']['i'] ),
                       '__toString' => array( 'exception'=>0, 'return' => $aBuffer64['max']['s'] ),
                        'getLength' => array( 'exception'=>0, 'return' => strlen($aBuffer64['max']['s']) ),
                        )),
//array( 'label'=>'TEST: range -9223372036854775808'      , 'test'=>'-9223372036854775808' ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => $aBuffer64['min']['i'] ),
                       '__toString' => array( 'exception'=>0, 'return' => $aBuffer64['min']['s'] ),
                        'getLength' => array( 'exception'=>0, 'return' => strlen($aBuffer64['min']['s']) ),
                        )),
//array( 'label'=>'TEST: range 9223372036854775808'       , 'test'=>'9223372036854775808' ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => $aBuffer64['maxo']['i'] ),
                       '__toString' => array( 'exception'=>0, 'return' => $aBuffer64['maxo']['s'] ),
                        'getLength' => array( 'exception'=>0, 'return' => strlen($aBuffer64['maxo']['s']) ),
                        )),
//array( 'label'=>'TEST: range -9223372036854775809'      , 'test'=>'-9223372036854775809' ),
array( 'expected'=>array(  'exception' => 0,
                          'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                         'getValue' => array( 'exception'=>0, 'return' => $aBuffer64['mino']['i'] ),
                       '__toString' => array( 'exception'=>0, 'return' => $aBuffer64['mino']['s'] ),
                        'getLength' => array( 'exception'=>0, 'return' => strlen($aBuffer64['mino']['s']) ),
                        )),
//array( 'label'=>'TEST: 128M'                             , 'test'=>'128M'),
array( 'expected'=>array(  'exception' => 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        )),
//array( 'label'=>'TEST: 0x20'                             , 'test'=>chr(0x20)),
array( 'expected'=>array(  'exception' => 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        )),
//array( 'label'=>'TEST: string empty'                     , 'test'=>''),
array( 'expected'=>array(  'exception' => 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        )),
//array( 'label'=>'TEST: string empty with space'          , 'test'=>' '),
array( 'expected'=>array(  'exception' => 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        )),
//array( 'label'=>'TEST: string "This is a simple string"' , 'test'=>'This is a simple string'),
array( 'expected'=>array(  'exception' => 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        )),
//array( 'label'=>'TEST: Iñtërnâtiônàlizætiøn'             , 'test'=>'Iñtërnâtiônàlizætiøn'),
array( 'expected'=>array(  'exception' => 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        )),
//array( 'label'=>'TEST: mail user+mailbox/department=shipping@café.glacé.com' , 'test'=>'user+mailbox/department=shipping@café.glacé.com'),
array( 'expected'=>array(  'exception' => 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        )),
//array( 'label'=>'TEST: hostname domain.com'              , 'test'=>'domain.com'),
array( 'expected'=>array(  'exception' => 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                         'getValue' => array( 'exception'=>0, 'return' => NULL ),
                       '__toString' => array( 'exception'=>0, 'return' => '' ),
                        'getLength' => array( 'exception'=>0, 'return' => 0 ),
                        )),
);