<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = [
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 5.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '5' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 5.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '5' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 5.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '5' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 5.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '5' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => false ],
                         'getValue' => [ 'exception' => 0, 'return' => null ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => false ],
                         'getValue' => [ 'exception' => 0, 'return' => null ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => false ],
                         'getValue' => [ 'exception' => 0, 'return' => null ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => -5.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '-5' ],
                        'getLength' => [ 'exception' => 0, 'return' => 2 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => -5.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '-5' ],
                        'getLength' => [ 'exception' => 0, 'return' => 2 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => -5.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '-5' ],
                        'getLength' => [ 'exception' => 0, 'return' => 2 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => -5.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '-5' ],
                        'getLength' => [ 'exception' => 0, 'return' => 2 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => false ],
                         'getValue' => [ 'exception' => 0, 'return' => null ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => false ],
                         'getValue' => [ 'exception' => 0, 'return' => null ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => false ],
                         'getValue' => [ 'exception' => 0, 'return' => null ],
                       '__toString' => [ 'exception' => 0, 'return' => '' ],
                        'getLength' => [ 'exception' => 0, 'return' => 0 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 0.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '0' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 0.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '0' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ] ]],
[ 'expected' => [  'exception' => 0,
                          'isvalid' => [ 'exception' => 0, 'return' => true ],
                         'getValue' => [ 'exception' => 0, 'return' => 0.0 ],
                       '__toString' => [ 'exception' => 0, 'return' => '0' ],
                        'getLength' => [ 'exception' => 0, 'return' => 1 ] ]],
];
