<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = array(
//array( 'label'=>'TEST: EMPTY'                                             , 'test' => ''),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 0xC00002EB'                                             , 'test' => 0xC00002EB),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 3221226219'                                             , 'test' => 3221226219),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 030000001353'                                             , 'test' => 030000001353),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: .'                                                 , 'test' => '.'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ..'                                                , 'test' => '..'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ...'                                               , 'test' => '...'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193'                                               , 'test' => '193'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193.'                                              , 'test' => '193.'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: .193'                                              , 'test' => '.193'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193.168'                                           , 'test' => '193.168'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193.168.'                                          , 'test' => '193.168.'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: .193.168'                                          , 'test' => '.193.168'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193.168.33'                                        , 'test' => '193.168.33'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193.168.33.'                                       , 'test' => '193.168.33.'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: .193.168.33'                                       , 'test' => '.193.168.33'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193.168.33.9.'                                     , 'test' => '193.168.33.9.'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: .193.168.33.9'                                     , 'test' => '.193.168.33.9'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193.168.33.9.1'                                    , 'test' => '193.168.33.9.1'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193..33.9'                                         , 'test' => '193..33.9'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193.168..9'                                        , 'test' => '193.168..9'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: 193...9'                                           , 'test' => '193...9'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ipv4 binary 11000000.00000000.00000010.11101011'   , 'test' => '11000000.00000000.00000010.11101011'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '192.0.2.235' ),
                        '__toString' => array( 'exception'=>0, 'return' => '192.0.2.235' ) )),
//array( 'label'=>'TEST: ipv4 octal 0300.0000.0002.0353'                    , 'test' => '0300.0000.0002.0353'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '192.0.2.235' ),
                        '__toString' => array( 'exception'=>0, 'return' => '192.0.2.235' ) )),
//array( 'label'=>'TEST: ipv4 hex 0A.1B.ZC.3D'                              , 'test' => '0A.1B.ZC.3D'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ipv4 256.168.33.9'                                 , 'test' => '256.168.33.9'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ipv4 193.256.33.9'                                 , 'test' => '193.256.33.9'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ipv4 193.168.256.9'                                , 'test' => '193.168.256.9'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ipv4 193.168.33.256'                               , 'test' => '193.168.33.256'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ipv4 193.168.33.9/8'                               , 'test' => '193.168.33.9/8'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ipv6 2001:41D0:1:2E4e::/64'                        , 'test' => '2001:41D0:1:2E4e::/64'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ipv6 2001:Zb8:0:85a3::ac1f:8001'                   , 'test' => '2001:Zb8:0:85a3::ac1f:8001'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => FALSE ),
                          'getValue' => array( 'exception'=>0, 'return' => NULL ),
                        '__toString' => array( 'exception'=>0, 'return' => '' ) )),
//array( 'label'=>'TEST: ipv4 hex 0A.1B.2C.3D'                              , 'test' => '0A.1B.2C.3D'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '10.27.44.61' ),
                        '__toString' => array( 'exception'=>0, 'return' => '10.27.44.61' ) )),
//array( 'label'=>'TEST: ipv4 193.168.33.9'                                 , 'test' => '193.168.33.9'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '193.168.33.9' ),
                        '__toString' => array( 'exception'=>0, 'return' => '193.168.33.9' ) )),
//array( 'label'=>'TEST: ipv6 2001:0db8:0000:0000:0000:ff00:0042:8329'      , 'test' => '2001:0db8:0000:0000:0000:ff00:0042:8329'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '2001:0db8:0000:0000:0000:ff00:0042:8329' ),
                        '__toString' => array( 'exception'=>0, 'return' => '2001:0db8:0000:0000:0000:ff00:0042:8329' ) )),
//array( 'label'=>'TEST: ipv6 2001:db8:0:0:0:ff00:42:8329'                  , 'test' => '2001:db8:0:0:0:ff00:42:8329'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '2001:db8:0:0:0:ff00:42:8329' ),
                        '__toString' => array( 'exception'=>0, 'return' => '2001:db8:0:0:0:ff00:42:8329' ) )),
//array( 'label'=>'TEST: ipv6 2001:0db8::ff00:0042:8329'                    , 'test' => '2001:0db8::ff00:0042:8329'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '2001:0db8::ff00:0042:8329' ),
                        '__toString' => array( 'exception'=>0, 'return' => '2001:0db8::ff00:0042:8329' ) )),
//array( 'label'=>'TEST: ipv6 2001:db8::ff00:42:8329'                       , 'test' => '2001:db8::ff00:42:8329'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '2001:db8::ff00:42:8329' ),
                        '__toString' => array( 'exception'=>0, 'return' => '2001:db8::ff00:42:8329' ) )),
//array( 'label'=>'TEST: ipv6 0000:0000:0000:0000:0000:0000:0000:0001'      , 'test' => '0000:0000:0000:0000:0000:0000:0000:0001'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '0000:0000:0000:0000:0000:0000:0000:0001' ),
                        '__toString' => array( 'exception'=>0, 'return' => '0000:0000:0000:0000:0000:0000:0000:0001' ) )),
//array( 'label'=>'TEST: ipv6 0:0:0:0:0:0:0:1'                              , 'test' => '0:0:0:0:0:0:0:1'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '0:0:0:0:0:0:0:1' ),
                        '__toString' => array( 'exception'=>0, 'return' => '0:0:0:0:0:0:0:1' ) )),
//array( 'label'=>'TEST: ipv6 ::0001'                                       , 'test' => '::0001'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '::0001' ),
                        '__toString' => array( 'exception'=>0, 'return' => '::0001' ) )),
//array( 'label'=>'TEST: ipv6 ::1'                                          , 'test' => '::1'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '::1' ),
                        '__toString' => array( 'exception'=>0, 'return' => '::1' ) )),
//array( 'label'=>'TEST: ipv6 ::'                                           , 'test' => '::'),
array( 'expected'=>array( 'exception'=> 0,
                           'isvalid' => array( 'exception'=>0, 'return' => TRUE ),
                          'getValue' => array( 'exception'=>0, 'return' => '::' ),
                        '__toString' => array( 'exception'=>0, 'return' => '::' ) )),
);