<?php
// 'Exception'=> 0:none, 1:PHPUnit_Framework_Error_Warning, 2:PHPUnit_Framework_Error_Notice, 3:\Exception
$this->_aTests[self::KEY_RESULT] = [
//// Non quoted valid
//array( 'label'=>'TEST: Abc' , 'test'=>'Abc' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => 'Abc' ],
                         '__toString' => [ 'exception' => 0, 'return' => 'Abc' ],
                          'getLength' => [ 'exception' => 0, 'return' => 3 ],
                             'getRaw' => [ 'exception' => 0, 'return' => 'Abc' ] ]],
//array( 'label'=>'TEST: Abc.123' , 'test'=>'Abc.123' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => 'Abc.123' ],
                         '__toString' => [ 'exception' => 0, 'return' => 'Abc.123' ],
                          'getLength' => [ 'exception' => 0, 'return' => 7 ],
                             'getRaw' => [ 'exception' => 0, 'return' => 'Abc.123' ] ]],
//array( 'label'=>'TEST: 123' , 'test'=>'123' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '123' ],
                         '__toString' => [ 'exception' => 0, 'return' => '123' ],
                          'getLength' => [ 'exception' => 0, 'return' => 3 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '123' ] ]],
//array( 'label'=>'TEST: 123-Abc' , 'test'=>'123-Abc' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '123-Abc' ],
                         '__toString' => [ 'exception' => 0, 'return' => '123-Abc' ],
                          'getLength' => [ 'exception' => 0, 'return' => 7 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '123-Abc' ] ]],
//array( 'label'=>'TEST: 12.-.Abc' , 'test'=>'12.-.Abc' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '12.-.Abc' ],
                         '__toString' => [ 'exception' => 0, 'return' => '12.-.Abc' ],
                          'getLength' => [ 'exception' => 0, 'return' => 8 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '12.-.Abc' ] ]],
//array( 'label'=>'TEST: user+mailbox' , 'test'=>'user+mailbox' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => 'user+mailbox' ],
                         '__toString' => [ 'exception' => 0, 'return' => 'user+mailbox' ],
                          'getLength' => [ 'exception' => 0, 'return' => 12 ],
                             'getRaw' => [ 'exception' => 0, 'return' => 'user+mailbox' ] ]],
//array( 'label'=>'TEST: customer/department=shipping' , 'test'=>'customer/department=shipping' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => 'customer/department=shipping' ],
                         '__toString' => [ 'exception' => 0, 'return' => 'customer/department=shipping' ],
                          'getLength' => [ 'exception' => 0, 'return' => 28 ],
                             'getRaw' => [ 'exception' => 0, 'return' => 'customer/department=shipping' ] ]],
//array( 'label'=>'TEST: user+mailbox/department=shipping' , 'test'=>'user+mailbox/department=shipping' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => 'user+mailbox/department=shipping' ],
                         '__toString' => [ 'exception' => 0, 'return' => 'user+mailbox/department=shipping' ],
                          'getLength' => [ 'exception' => 0, 'return' => 32 ],
                             'getRaw' => [ 'exception' => 0, 'return' => 'user+mailbox/department=shipping' ] ]],
//array( 'label'=>'TEST: !#$%&\'*+-/=?^_`.{|}~' , 'test'=>'!#$%&\'*+-/=?^_`.{|}~' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '!#$%&\'*+-/=?^_`.{|}~' ],
                         '__toString' => [ 'exception' => 0, 'return' => '!#$%&\'*+-/=?^_`.{|}~' ],
                          'getLength' => [ 'exception' => 0, 'return' => 20 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '!#$%&\'*+-/=?^_`.{|}~' ] ]],
//array( 'label'=>'TEST: !def!xyz%abc' , 'test'=>'!def!xyz%abc' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '!def!xyz%abc' ],
                         '__toString' => [ 'exception' => 0, 'return' => '!def!xyz%abc' ],
                          'getLength' => [ 'exception' => 0, 'return' => 12 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '!def!xyz%abc' ] ]],
//array( 'label'=>'TEST: _somename' , 'test'=>'_somename' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '_somename' ],
                         '__toString' => [ 'exception' => 0, 'return' => '_somename' ],
                          'getLength' => [ 'exception' => 0, 'return' => 9 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '_somename' ] ]],
//array( 'label'=>'TEST: Abc.example.com' , 'test'=>'Abc.example.com' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => 'Abc.example.com' ],
                         '__toString' => [ 'exception' => 0, 'return' => 'Abc.example.com' ],
                          'getLength' => [ 'exception' => 0, 'return' => 15 ],
                             'getRaw' => [ 'exception' => 0, 'return' => 'Abc.example.com' ] ]],
//// Non quoted invalid
//array( 'label'=>'TEST: Abc..123' , 'test'=>'Abc..123' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => 'Abc..123' ] ]],
//array( 'label'=>'TEST: Abc@def' , 'test'=>'Abc@def' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => 'Abc@def' ] ]],
//array( 'label'=>'TEST: Abc\@def' , 'test'=>'Abc\@def' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => 'Abc\@def' ] ]],
//array( 'label'=>'TEST: Fred Bloggs' , 'test'=>'Fred Bloggs' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => 'Fred Bloggs' ] ]],
//array( 'label'=>'TEST: Fred\ Bloggs' , 'test'=>'Fred\ Bloggs' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => 'Fred\ Bloggs' ] ]],
//array( 'label'=>'TEST: Joe.\\Blow' , 'test'=>'Joe.\\Blow' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => 'Joe.\\Blow' ] ]],
//array( 'label'=>'TEST: Abc.' , 'test'=>'Abc.' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => 'Abc.' ] ]],
//array( 'label'=>'TEST: .Abc' , 'test'=>'.Abc' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => '.Abc' ] ]],
//// Quoted valid
//array( 'label'=>'TEST: quoted Abc' , 'test'=>'"Abc"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"Abc"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"Abc"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 5 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"Abc"' ] ]],
//array( 'label'=>'TEST: quoted Abc.123' , 'test'=>'"Abc.123"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"Abc.123"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"Abc.123"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 9 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"Abc.123"' ] ]],
//array( 'label'=>'TEST: quoted 123' , 'test'=>'"123"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"123"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"123"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 5 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"123"' ] ]],
//array( 'label'=>'TEST: quoted 123-Abc' , 'test'=>'"123-Abc"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"123-Abc"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"123-Abc"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 9 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"123-Abc"' ] ]],
//array( 'label'=>'TEST: quoted 12.-.Abc' , 'test'=>'"12.-.Abc"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"12.-.Abc"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"12.-.Abc"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 10 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"12.-.Abc"' ] ]],
//array( 'label'=>'TEST: quoted user+mailbox' , 'test'=>'"user+mailbox"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"user+mailbox"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"user+mailbox"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 14 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"user+mailbox"' ] ]],
//array( 'label'=>'TEST: quoted customer/department=shipping' , 'test'=>'"customer/department=shipping"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"customer/department=shipping"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"customer/department=shipping"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 30 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"customer/department=shipping"' ] ]],
//array( 'label'=>'TEST: quoted user+mailbox/department=shipping' , 'test'=>'"user+mailbox/department=shipping"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"user+mailbox/department=shipping"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"user+mailbox/department=shipping"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 34 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"user+mailbox/department=shipping"' ] ]],
//array( 'label'=>'TEST: quoted !#$%&\'*+-/=?^_`.{|}~' , 'test'=>'"!#$%&\'*+-/=?^_`.{|}~"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"!#$%&\'*+-/=?^_`.{|}~"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"!#$%&\'*+-/=?^_`.{|}~"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 22 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"!#$%&\'*+-/=?^_`.{|}~"' ] ]],
//array( 'label'=>'TEST: quoted !def!xyz%abc' , 'test'=>'"!def!xyz%abc"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"!def!xyz%abc"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"!def!xyz%abc"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 14 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"!def!xyz%abc"' ] ]],
//array( 'label'=>'TEST: quoted _somename' , 'test'=>'"_somename"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"_somename"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"_somename"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 11 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"_somename"' ] ]],
//array( 'label'=>'TEST: quoted Abc@def' , 'test'=>'"Abc@def"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"Abc@def"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"Abc@def"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 9 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"Abc@def"' ] ]],
//array( 'label'=>'TEST: quoted Abc\@def' , 'test'=>'"Abc\@def"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"Abc\@def"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"Abc\@def"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 10 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"Abc\@def"' ] ]],
//array( 'label'=>'TEST: quoted Fred Bloggs' , 'test'=>'"Fred Bloggs"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"Fred Bloggs"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"Fred Bloggs"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 13 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"Fred Bloggs"' ] ]],
//array( 'label'=>'TEST: quoted Fred\ Bloggs' , 'test'=>'"Fred\ Bloggs"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"Fred\ Bloggs"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"Fred\ Bloggs"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 14 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"Fred\ Bloggs"' ] ]],
//array( 'label'=>'TEST: quoted Joe.\\Blow' , 'test'=>'"Joe.\\Blow"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"Joe.\\Blow"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"Joe.\\Blow"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 11 ],
                             'getRaw' => [ 'exception' => 0, 'return' => '"Joe.\\Blow"' ] ]],
//array( 'label'=>'TEST: quoted Abc.example.com' , 'test'=>'"Abc.example.com"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => true ],
                           'getValue' => [ 'exception' => 0, 'return' => '"Abc.example.com"' ],
                         '__toString' => [ 'exception' => 0, 'return' => '"Abc.example.com"' ],
                          'getLength' => [ 'exception' => 0, 'return' => 17 ],
                            'getRaw' => [ 'exception' => 0, 'return' => '"Abc.example.com"' ] ]],
//// Quoted invalid
//array( 'label'=>'TEST: quoted Abc..123' , 'test'=>'"Abc..123"' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => '"Abc..123"' ] ]],
//array( 'label'=>'TEST: quoted Abc.' , 'test'=>'"Abc."' ),
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => '"Abc."' ] ]],
//array( 'label'=>'TEST: quoted .Abc' , 'test'=>'".Abc"' )
[ 'expected' => [ 'exception' => 0,
                            'isvalid' => [ 'exception' => 0, 'return' => false ],
                           'getValue' => [ 'exception' => 0, 'return' => null ],
                         '__toString' => [ 'exception' => 0, 'return' => '' ],
                          'getLength' => [ 'exception' => 0, 'return' => 0 ],
                            'getRaw' => [ 'exception' => 0, 'return' => '".Abc"' ] ]],
];
